// Generated by gotsx from the Go host modules. DO NOT EDIT.

declare module "host:data" {
  /** action: callable from islands (POST, same-origin); throws on a validation error */
  export function like(id: string): Promise<number>;
  export function stats(): Stats;
  export function trending(): Model[];
  export const models: ModelStore;
}

declare module "host:intl" {
  export function fmtDate(iso: string): string;
  export function fmtNumber(n: number): string;
  export function now(): string;
}

declare module "host:data" {
  export interface Stats {
    total: number;
    likes: number;
  }
  export interface Model {
    id: string;
    title: string;
    author: string;
    desc: string;
    likes: number;
    tags: string[];
    createdAt: string;
  }
  export interface ModelStore {
    get(id: string): Model;
    like(id: string): number;
    list(): Model[];
    search(q: string): Model[];
  }
}
