// Generated by gotsx from the Go host modules. DO NOT EDIT.

declare module "host:data" {
  export function stats(): Stats;
  export function trending(): Model[];
  export const models: ModelStore;
}

declare module "host:intl" {
  export function fmtDate(arg0: string): string;
  export function fmtNumber(arg0: number): string;
  export function now(): string;
}

declare module "host:data" {
  export interface Stats {
    total: number;
    likes: number;
  }
  export interface Model {
    id: string;
    title: string;
    author: string;
    desc: string;
    likes: number;
    tags: string[];
    createdAt: string;
  }
  export interface ModelStore {
    get(arg0: string): Model;
    like(arg0: string): number;
    list(): Model[];
    search(arg0: string): Model[];
  }
}
