package compiler

// The server half of typed actions: generates gen.HostActions for the module methods marked as actions in host.json —
// decode the JSON arguments by Go type, inject *gotsx.Req (if any), call the method, and normalize (T, error) / T / error / none to (any, error).

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// GenActions produces the content of gen/actions_gen.go; with no actions it still emits an empty table so main.go can always reference gen.HostActions
func GenActions(c *Checker, pkg, runtimeImport, hostImport string) (string, error) {
	type item struct {
		mod string
		hm  *HostModT
		m   *HostMember
	}
	var items []item
	mods := make([]string, 0, len(c.Host.Modules))
	for n := range c.Host.Modules {
		mods = append(mods, n)
	}
	sort.Strings(mods)
	for _, mn := range mods {
		hm := c.Host.Modules[mn]
		names := make([]string, 0, len(hm.Members))
		for n := range hm.Members {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			if m := hm.Members[n]; m.Kind == "method" && m.Action {
				items = append(items, item{mn, hm, m})
			}
		}
	}
	var b strings.Builder
	b.WriteString("// Code generated by gotsx. DO NOT EDIT.\n\npackage " + pkg + "\n\n")
	if len(items) == 0 {
		fmt.Fprintf(&b, "import gotsx %q\n\n// HostActions: no host module lists Actions yet (see gotsx.HostModule.Actions)\nvar HostActions []gotsx.HostAction\n", runtimeImport)
		return b.String(), nil
	}
	fmt.Fprintf(&b, "import (\n\t\"encoding/json\"\n\n\tgotsx %q\n\thost %q\n)\n\n", runtimeImport, hostImport)
	b.WriteString("// HostActions: pass to gotsx.Options{HostActions: gen.HostActions}; islands call them as typed functions\nvar HostActions = []gotsx.HostAction{\n")
	for _, it := range items {
		fmt.Fprintf(&b, "\t{Module: %q, Name: %q, Fn: func(req *gotsx.Req, args []json.RawMessage) (any, error) {\n", it.mod, it.m.Name)
		var call []string
		if it.m.Req {
			call = append(call, "req")
		}
		for i, p := range it.m.Params {
			gt := p.Go
			if bad := foreignPkg(gt); bad != "" {
				return "", fmt.Errorf("action %s.%s: parameter %d has type %s from package %q; actions may only take builtin types and host types", it.mod, it.m.Name, i, gt, bad)
			}
			fmt.Fprintf(&b, "\t\tvar a%d %s\n\t\tif err := gotsx.Arg(args, %d, &a%d); err != nil {\n\t\t\treturn nil, err\n\t\t}\n", i, gt, i, i)
			call = append(call, "a"+strconv.Itoa(i))
		}
		expr := it.hm.Go + "." + it.m.Go + "(" + strings.Join(call, ", ") + ")"
		switch {
		case it.m.Ret != nil && it.m.Throws:
			fmt.Fprintf(&b, "\t\treturn %s\n", expr)
		case it.m.Ret != nil:
			fmt.Fprintf(&b, "\t\treturn %s, nil\n", expr)
		case it.m.Throws:
			fmt.Fprintf(&b, "\t\treturn nil, %s\n", expr)
		default:
			fmt.Fprintf(&b, "\t\t%s\n\t\treturn nil, nil\n", expr)
		}
		b.WriteString("\t}},\n")
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// foreignPkg: the package qualifier in a Go type string other than host (e.g. time.Time → "time"); "" if none
func foreignPkg(goType string) string {
	t := strings.TrimLeft(goType, "*[]")
	t = strings.TrimPrefix(t, "map[string]")
	t = strings.TrimLeft(t, "*[]")
	if i := strings.IndexByte(t, '.'); i >= 0 {
		if pkg := t[:i]; pkg != "host" {
			return pkg
		}
	}
	return ""
}
