package compiler

// 编译流程: 扫描 app/**/*.tsx → 解析 → 检查 → Go 后端(gen/*.go + routes) → JS 后端(gen/client/*.js)

import (
	"encoding/json"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Config struct {
	AppDir     string // .../example/app
	OutDir     string // .../example/gen
	Module     string // Go module path of the app, e.g. gotsx/example
	HostPkg    string // Go import path of host package
	RuntimePkg string // gotsx/runtime
	ClientFS   fs.FS  // runtime.js / loader.js / idiomorph.esm.js
}

type Report struct {
	Modules []string
	Routes  []string
	Islands []string
}

func Build(cfg Config) (*Report, error) {
	var files []string
	err := filepath.WalkDir(cfg.AppDir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() && d.Name() == ".gen" {
			return filepath.SkipDir
		}
		if !d.IsDir() && strings.HasSuffix(p, ".tsx") {
			files = append(files, p)
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(files)
	if len(files) == 0 {
		return nil, fmt.Errorf("%s 下没有 .tsx 文件", cfg.AppDir)
	}

	c, err := NewChecker(ReadHostJSON(cfg.AppDir))
	if err != nil {
		return nil, err
	}
	var perr []string
	for _, f := range files {
		src, err := os.ReadFile(f)
		if err != nil {
			return nil, err
		}
		m, err := ParseModule(string(src), f)
		if err != nil {
			perr = append(perr, "  "+err.Error())
			continue
		}
		c.AddModule(m)
	}
	if len(perr) > 0 {
		return nil, fmt.Errorf("语法错误:\n%s", strings.Join(perr, "\n"))
	}
	if err := c.CheckAll(); err != nil {
		return nil, err
	}

	rep := &Report{}
	os.MkdirAll(cfg.OutDir, 0o755)
	clientDir := filepath.Join(cfg.OutDir, "client")
	os.MkdirAll(clientDir, 0o755)
	// 清掉旧产物
	old, _ := filepath.Glob(filepath.Join(cfg.OutDir, "*_gen.go"))
	for _, f := range old {
		os.Remove(f)
	}
	oldJS, _ := filepath.Glob(filepath.Join(clientDir, "*.js"))
	for _, f := range oldJS {
		os.Remove(f)
	}

	var genErrs []string
	pagesDir := filepath.Join(cfg.AppDir, "pages")
	var routes []string
	for _, f := range files {
		m := c.Modules[f]
		rel, _ := filepath.Rel(cfg.AppDir, f)
		rep.Modules = append(rep.Modules, rel)
		src, err := GenGo(c, m, "gen", cfg.RuntimePkg, cfg.HostPkg)
		if err != nil {
			genErrs = append(genErrs, "  "+err.Error())
			continue
		}
		formatted, ferr := format.Source([]byte(src))
		if ferr != nil {
			genErrs = append(genErrs, fmt.Sprintf("  %s: 生成的 Go 代码无法格式化: %v\n%s", rel, ferr, numbered(src)))
			continue
		}
		name := strings.TrimSuffix(rel, ".tsx")
		name = strings.NewReplacer("/", "_", "[", "_", "]", "_", ".", "_", "-", "_").Replace(name)
		if err := os.WriteFile(filepath.Join(cfg.OutDir, name+"_gen.go"), formatted, 0o644); err != nil {
			return nil, err
		}
		if m.Kind != "server" {
			js, err := GenJS(c, m)
			if err != nil {
				genErrs = append(genErrs, "  "+err.Error())
				continue
			}
			if err := os.WriteFile(filepath.Join(clientDir, m.Name+".js"), []byte(js), 0o644); err != nil {
				return nil, err
			}
			if m.Kind == "client" {
				rep.Islands = append(rep.Islands, m.Name)
			}
		}
		if strings.HasPrefix(f, pagesDir+string(filepath.Separator)) && m.Kind == "server" {
			if m.Default == nil || m.Default.Kind != SComp {
				genErrs = append(genErrs, fmt.Sprintf("  %s: 页面必须 export default 一个组件", rel))
				continue
			}
			if m.Default.Comp.Props != c.pageProps {
				genErrs = append(genErrs, fmt.Sprintf("  %s: 页面组件的 props 必须是 PageProps", rel))
				continue
			}
			pattern, segs := routeOf(pagesDir, f)
			routes = append(routes, fmt.Sprintf("\t{Pattern: %q, Segs: %s, Render: func(p gotsx.PageProps) gotsx.Node { return %s(p) }},", pattern, goStrSlice(segs), m.Default.Go))
			rep.Routes = append(rep.Routes, pattern)
		}
	}
	if len(genErrs) > 0 {
		return nil, fmt.Errorf("生成失败:\n%s", strings.Join(genErrs, "\n"))
	}
	rt := fmt.Sprintf("// Code generated by gotsx. DO NOT EDIT.\n\npackage gen\n\nimport gotsx %q\n\nvar Routes = []gotsx.Route{\n%s\n}\n", cfg.RuntimePkg, strings.Join(routes, "\n"))
	if err := os.WriteFile(filepath.Join(cfg.OutDir, "routes_gen.go"), []byte(rt), 0o644); err != nil {
		return nil, err
	}
	ij, _ := json.Marshal(rep.Islands)
	if err := os.WriteFile(filepath.Join(clientDir, "islands.json"), ij, 0o644); err != nil {
		return nil, err
	}
	// 内嵌客户端资源, 支持单二进制部署
	assets := "// Code generated by gotsx. DO NOT EDIT.\n\npackage gen\n\n" +
		"import (\n\t\"embed\"\n\t\"io/fs\"\n)\n\n" +
		"//go:embed client\n" +
		"var clientEmbed embed.FS\n\n" +
		"// ClientFS 是内嵌的客户端资源(单二进制部署用)\n" +
		"var ClientFS, _ = fs.Sub(clientEmbed, \"client\")\n"
	if err := os.WriteFile(filepath.Join(cfg.OutDir, "assets_gen.go"), []byte(assets), 0o644); err != nil {
		return nil, err
	}
	// 客户端运行时
	for _, n := range []string{"runtime.js", "loader.js", "idiomorph.esm.js"} {
		b, err := fs.ReadFile(cfg.ClientFS, n)
		if err != nil {
			return nil, fmt.Errorf("读取内嵌 %s: %w", n, err)
		}
		if err := os.WriteFile(filepath.Join(clientDir, n), b, 0o644); err != nil {
			return nil, err
		}
	}
	return rep, nil
}

func routeOf(pagesDir, file string) (string, []string) {
	r, _ := filepath.Rel(pagesDir, file)
	r = strings.TrimSuffix(r, ".server.tsx")
	r = strings.TrimSuffix(r, "index")
	r = strings.Trim(filepath.ToSlash(r), "/")
	var segs []string
	if r != "" {
		for _, s := range strings.Split(r, "/") {
			if strings.HasPrefix(s, "[") && strings.HasSuffix(s, "]") {
				s = "{" + s[1:len(s)-1] + "}"
			}
			segs = append(segs, s)
		}
	}
	return "/" + strings.Join(segs, "/"), segs
}

func goStrSlice(ss []string) string {
	if len(ss) == 0 {
		return "nil"
	}
	var q []string
	for _, s := range ss {
		q = append(q, fmt.Sprintf("%q", s))
	}
	return "[]string{" + strings.Join(q, ", ") + "}"
}

func numbered(src string) string {
	var b strings.Builder
	for i, ln := range strings.Split(src, "\n") {
		fmt.Fprintf(&b, "%4d  %s\n", i+1, ln)
	}
	return b.String()
}
