package compiler

// Go 后端: 组件 → Go 函数, JSX → gotsx 节点表达式, hooks → SSR 单趟语义, host:* → 直接调用。

import (
	"fmt"
	"html"
	"strconv"
	"strings"
)

type goGen struct {
	c        *Checker
	m        *Module
	b        strings.Builder
	ind      int
	needHost bool
	hostPkg  string
	tmp      int
	errs     []error
	curRet   Type
	lastMark Pos
}

type genError struct {
	Pos Pos
	Msg string
}

func (e *genError) Error() string { return fmt.Sprintf("%s: %s", e.Pos, e.Msg) }

func (g *goGen) fail(pos Pos, format string, args ...any) {
	panic(&genError{Pos: pos, Msg: fmt.Sprintf(format, args...)})
}

func (g *goGen) line(format string, args ...any) {
	g.b.WriteString(strings.Repeat("\t", g.ind))
	fmt.Fprintf(&g.b, format, args...)
	g.b.WriteByte('\n')
}

func (g *goGen) newTmp() string {
	g.tmp++
	return fmt.Sprintf("_t%d", g.tmp)
}

// mark: 注入 //line 指令, 让下一行 Go 代码的报错/panic 指回 .tsx 源码位置
func (g *goGen) mark(pos Pos) {
	if pos.Line > 0 && pos.File != "" && pos != g.lastMark {
		g.lastMark = pos
		fmt.Fprintf(&g.b, "//line %s:%d\n", pos.File, pos.Line)
	}
}

func stmtPos(s Stmt) Pos {
	switch d := s.(type) {
	case *VarDecl:
		return d.Pos
	case *ReturnStmt:
		return d.Pos
	case *IfStmt:
		return d.Pos
	case *ForOfStmt:
		return d.Pos
	case *ForStmt:
		return d.Pos
	case *WhileStmt:
		return d.Pos
	case *SwitchStmt:
		return d.Pos
	case *BreakStmt:
		return d.Pos
	case *ContinueStmt:
		return d.Pos
	case *ExprStmt:
		return d.Pos
	case *ThrowStmt:
		return d.Pos
	case *TryStmt:
		return d.Pos
	case *Block:
		return d.Pos
	case *FuncDecl:
		return d.Pos
	}
	return Pos{}
}

// GenGo 生成一个模块的 Go 源码
func GenGo(c *Checker, m *Module, pkg, runtimeImport, hostImport string) (src string, err error) {
	g := &goGen{c: c, m: m, hostPkg: "host"}
	defer func() {
		if r := recover(); r != nil {
			if ge, ok := r.(*genError); ok {
				err = ge
				return
			}
			panic(r)
		}
	}()
	var body strings.Builder
	g.genTypes()
	for _, s := range m.Stmts {
		switch d := s.(type) {
		case *FuncDecl:
			if d.Async || (!d.Comp && (clientOnly(d.Body.Stmts) || readsStore(d.Body.Stmts))) {
				continue // 只进 JS 后端(a helper that reads a store has no render context on the server: browser only, like DOM code)
			}
			g.genFunc(d)
		case *VarDecl:
			sym := d.Pat.Sym
			if d.Hook == "createStore" { // the store: its initial value; a page's seed(store, value) overrides it per request
				st := sym.Type.(*StoreT)
				g.mark(d.Pos)
				g.line("var %s = gotsx.NewStore(%q, %s)", sym.Go, sym.Go, g.conv(d.Init.(*Call).Args[0], st.State))
				g.line("")
				continue
			}
			if isNode(sym.Type) {
				g.line("var %s gotsx.Node = %s", sym.Go, g.toNode(d.Init, false))
			} else {
				g.line("var %s %s = %s", sym.Go, g.goType(sym.Type), g.conv(d.Init, sym.Type))
			}
			g.line("")
		}
	}
	body.WriteString(g.b.String())

	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by gotsx from %s. DO NOT EDIT.\n\npackage %s\n\nimport (\n\tgotsx %q\n", m.File, pkg, runtimeImport)
	if g.needHost {
		fmt.Fprintf(&out, "\thost %q\n", hostImport)
	}
	out.WriteString(")\n\nvar _ = gotsx.Num\n\n")
	out.WriteString(body.String())
	return out.String(), nil
}

// ---------- 类型 ----------

func (g *goGen) goType(t Type) string {
	switch x := t.(type) {
	case *Prim:
		switch x {
		case TString:
			return "string"
		case TNumber:
			return "float64"
		case TBool:
			return "bool"
		case TNode:
			return "gotsx.Node"
		case TRegExp:
			return "*gotsx.Regex"
		case TVoid:
			return ""
		}
		return "any"
	case *ArrT:
		return "[]" + g.goType(x.Elem)
	case *MapT:
		return "map[string]" + g.goType(x.Val)
	case *ObjT:
		if x.Host && !strings.HasPrefix(x.GoName, "gotsx.") { // framework builtin objects (Meta / Flash) live in the runtime package, not the host
			g.needHost = true
		}
		return x.GoName
	case *OptT:
		return g.goType(x.Elem)
	case *FnT:
		var ps []string
		for _, p := range x.Params {
			ps = append(ps, g.goType(p.Type))
		}
		ret := ""
		if x.Ret != nil && !x.Async {
			ret = g.goType(x.Ret)
		}
		return "func(" + strings.Join(ps, ", ") + ") " + ret
	case *SetterT:
		return "func(any)"
	case *StoreT:
		return "*gotsx.Store[" + g.goType(x.State) + "]"
	}
	return "any"
}

func (g *goGen) zero(t Type) string {
	switch x := unopt(t).(type) {
	case *Prim:
		switch x {
		case TString:
			return `""`
		case TNumber:
			return "0"
		case TBool:
			return "false"
		}
		return "nil"
	case *ObjT:
		return x.GoName + "{}"
	}
	return "nil"
}

func (g *goGen) genTypes() {
	seen := map[*ObjT]bool{}
	emit := func(t *ObjT) {
		if t == nil || seen[t] || t.Host || t.GoName == "" {
			return
		}
		seen[t] = true
		g.line("type %s struct {", t.GoName)
		g.ind++
		for _, f := range t.Fields {
			// 方言对象结构总是带 json tag: 保证 JSON.stringify 用原始键(如 @context), 不受 server/client 影响
			tag := fmt.Sprintf(" `json:%q`", f.Name)
			if isNode(f.Type) {
				tag = " `json:\"-\"`"
			}
			g.line("%s %s%s", f.Go, g.goType(f.Type), tag)
		}
		g.ind--
		g.line("}")
		g.line("")
	}
	for _, s := range g.m.Stmts {
		if d, ok := s.(*InterfaceDecl); ok {
			emit(d.T)
		}
	}
	for _, t := range g.m.AnonTypes {
		emit(t)
	}
}

// ---------- 函数 ----------

func (g *goGen) genFunc(d *FuncDecl) {
	g.mark(d.Pos)
	if d.Comp {
		comp := d.Sym.Comp
		props := comp.Props
		name := d.Sym.Go
		ctxParam := ""
		if g.m.Kind == "client" { // components of client modules render with the request context (store seeds)
			ctxParam = "_ctx *gotsx.Ctx, "
		}
		if g.m.Kind == "client" && d.Default {
			// 岛: 外壳 + 预渲染(the body runs when the island is written, with the context in hand)
			g.line("func %s(props %s) gotsx.Node {", name, props.GoName)
			g.line("\treturn gotsx.Island(%q, props, func(_ctx *gotsx.Ctx) { _ctx.N(%s_ssr(_ctx, props)) })", g.m.Name, name)
			g.line("}")
			g.line("")
			name += "_ssr"
		}
		g.line("func %s(%sprops %s) gotsx.Node {", name, ctxParam, props.GoName)
		g.ind++
		g.curRet = TNode
		if len(d.Params) > 0 {
			g.bindParam(d.Params[0].Pat, "props", props)
		}
		g.stmts(d.Body.Stmts)
		if !endsWithReturn(d.Body) {
			g.line("return nil")
		}
		g.ind--
		g.line("}")
		g.line("")
		return
	}
	ft := d.Sym.Type.(*FnT)
	g.line("func %s(%s) %s {", d.Sym.Go, g.paramList(d.Params, ft), g.goType(ft.Ret))
	g.ind++
	g.bindParams(d.Params, ft)
	saveRet := g.curRet
	g.curRet = ft.Ret
	g.stmts(d.Body.Stmts)
	g.curRet = saveRet
	g.ind--
	g.line("}")
	g.line("")
}

func endsWithReturn(b *Block) bool {
	if len(b.Stmts) == 0 {
		return false
	}
	_, ok := b.Stmts[len(b.Stmts)-1].(*ReturnStmt)
	return ok
}

func (g *goGen) paramList(params []*Param, ft *FnT) string {
	var ps []string
	for i, p := range params {
		name := "p" + strconv.Itoa(i)
		if p.Pat.Kind == PatIdent {
			name = p.Pat.Sym.Go
		}
		ps = append(ps, name+" "+g.goType(ft.Params[i].Type))
	}
	return strings.Join(ps, ", ")
}

// bindParams expands destructured parameters of plain functions (meta({ params }: PageProps) etc.): paramList names them pN, this binds the parts
func (g *goGen) bindParams(params []*Param, ft *FnT) {
	for i, p := range params {
		if p.Pat.Kind != PatIdent {
			g.bindParam(p.Pat, "p"+strconv.Itoa(i), ft.Params[i].Type)
		}
	}
}

// 解构参数: 生成 a := props.A 等
func (g *goGen) bindParam(pat *Pattern, src string, t Type) {
	switch pat.Kind {
	case PatIdent:
		if pat.Sym.Go != src {
			g.line("%s := %s", pat.Sym.Go, src)
			g.line("_ = %s", pat.Sym.Go)
		}
	case PatObject:
		for _, pp := range pat.Props {
			var ft Type = TAny
			access := src
			switch o := unopt(t).(type) {
			case *ObjT:
				f := o.Field(pp.Key)
				access = src + "." + f.Go
				ft = f.Type
				if numConv(f.GoType) {
					access = "float64(" + access + ")"
				}
				if numConvSlice(f.GoType) {
					access = "gotsx.Nums(" + access + ")"
				}
			case *MapT:
				access = src + "[" + strconv.Quote(pp.Key) + "]"
				ft = o.Val
			}
			if pp.Default != nil && pp.Pat.Kind == PatIdent {
				ft = unopt(ft)
				g.line("%s := %s", pp.Pat.Sym.Go, access)
				if def := g.conv(pp.Default, ft); def != g.zero(ft) { // 默认值就是零值的话不用写
					g.line("if %s == %s {", pp.Pat.Sym.Go, g.zero(ft))
					g.line("\t%s = %s", pp.Pat.Sym.Go, def)
					g.line("}")
				}
				g.line("_ = %s", pp.Pat.Sym.Go)
				continue
			}
			g.bindParam(pp.Pat, access, ft)
		}
	case PatArray:
		for i, el := range pat.Elems {
			var et Type = TAny
			if a, ok := unopt(t).(*ArrT); ok {
				et = a.Elem
			}
			g.bindParam(el, fmt.Sprintf("%s[%d]", src, i), et)
		}
	}
}

var numScalars = map[string]bool{"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true, "float32": true}

func numConv(goType string) bool { return numScalars[goType] }

// []int 这类数值切片 → []float64 需要逐元素转换(gotsx.Nums)
func numConvSlice(goType string) bool {
	return strings.HasPrefix(goType, "[]") && numScalars[strings.TrimPrefix(goType, "[]")]
}

// ---------- 语句 ----------

func (g *goGen) stmts(ss []Stmt) {
	for _, s := range ss {
		g.stmt(s)
	}
}

func (g *goGen) block(b *Block) {
	g.ind++
	g.stmts(b.Stmts)
	g.ind--
}

func (g *goGen) stmt(s Stmt) {
	g.mark(stmtPos(s))
	switch d := s.(type) {
	case *VarDecl:
		g.varDecl(d)
	case *ReturnStmt:
		fc := g.fnRet(d)
		if d.X == nil {
			g.line("return")
			return
		}
		if fc == nil || isNode(fc) {
			g.line("return %s", g.toNode(d.X, false))
			return
		}
		if fc == TVoid {
			g.line("%s", g.expr(d.X))
			g.line("return")
			return
		}
		g.line("return %s", g.conv(d.X, fc))
	case *IfStmt:
		g.line("if %s {", g.truthy(d.Cond))
		g.block(d.Then)
		if d.Else != nil {
			switch e := d.Else.(type) {
			case *Block:
				g.line("} else {")
				g.block(e)
			case *IfStmt:
				g.line("} else {")
				g.ind++
				g.stmt(e)
				g.ind--
			}
		}
		g.line("}")
	case *ForOfStmt:
		if d.Pat.Kind == PatIdent {
			g.line("for _, %s := range %s {", d.Pat.Sym.Go, g.expr(d.Iter))
			g.ind++
			g.line("_ = %s", d.Pat.Sym.Go)
			g.ind--
		} else {
			tmp := g.newTmp()
			g.line("for _, %s := range %s {", tmp, g.expr(d.Iter))
			g.ind++
			g.bindParam(d.Pat, tmp, d.Pat.T)
			g.ind--
		}
		g.block(d.Body)
		g.line("}")
	case *WhileStmt:
		g.line("for %s {", g.truthy(d.Cond))
		g.block(d.Body)
		g.line("}")
	case *ForStmt:
		g.forStmt(d)
	case *BreakStmt:
		g.line("break")
	case *ContinueStmt:
		g.line("continue")
	case *SwitchStmt:
		g.switchStmt(d)
	case *ExprStmt:
		g.exprStmt(d.X)
	case *Block:
		g.line("{")
		g.block(d)
		g.line("}")
	case *TryStmt:
		g.stmts(d.Body.Stmts)
		if d.Finally != nil {
			g.stmts(d.Finally.Stmts)
		}
	case *ThrowStmt:
		g.line("gotsx.Throw(%s)", g.expr(d.X))
	case *FuncDecl:
		ft := d.Sym.Type.(*FnT)
		if d.Async || clientOnly(d.Body.Stmts) {
			g.line("%s := %s", d.Sym.Go, g.stub(ft, strings.Split(g.paramList(d.Params, ft), ", ")))
			g.line("_ = %s", d.Sym.Go)
			return
		}
		g.line("%s := func(%s) %s {", d.Sym.Go, g.paramList(d.Params, ft), g.goType(ft.Ret))
		g.ind++
		g.bindParams(d.Params, ft)
		g.ind--
		saveRet := g.curRet
		g.curRet = ft.Ret
		g.block(d.Body)
		g.curRet = saveRet
		g.line("}")
		g.line("_ = %s", d.Sym.Go)
	case *InterfaceDecl, *TypeAlias, *EmptyStmt:
	default:
		g.fail(Pos{}, "Go backend: unsupported statement %T", s)
	}
}

// 当前函数的返回类型(通过 ReturnStmt 表达式的期望推断不了时用 nil)
func (g *goGen) fnRet(r *ReturnStmt) Type {
	return g.curRet
}

func (g *goGen) exprStmt(x Expr) {
	switch e := x.(type) {
	case *Call:
		if e.Kind == "hook:useEffect" || e.Kind == "hook:useEffectOnce" || e.Kind == "storeSet" || containsAwait(e) {
			return
		}
		if e.Kind == "host" && e.Host.Throws && e.Host.Ret == nil {
			g.line("gotsx.Check(%s)", g.hostCall(e, true))
			return
		}
		g.line("%s", g.expr(e))
	case *Assign:
		g.line("%s", g.assign(e))
	case *Update:
		g.line("%s", g.update(e))
	case *Unary:
		if e.Op == "delete" {
			g.line("%s", g.deleteKey(e))
			return
		}
		g.line("_ = %s", g.expr(x))
	case *AwaitExpr:
		return
	default:
		g.line("_ = %s", g.expr(x))
	}
}

// deleteKey: delete m[k] / delete m.k → delete(m, k)
func (g *goGen) deleteKey(e *Unary) string {
	switch t := e.X.(type) {
	case *Index:
		return "delete(" + g.expr(t.X) + ", " + g.expr(t.I) + ")"
	case *Member:
		return "delete(" + g.expr(t.X) + ", " + strconv.Quote(t.Name) + ")"
	}
	g.fail(e.Pos, "delete only works on a Record key")
	return ""
}

// simpleStmt: for 的 init / post 位置(Go 只接受简单语句)
func (g *goGen) simpleStmt(x Expr) string {
	switch e := x.(type) {
	case *Assign:
		return g.assign(e)
	case *Update:
		return g.update(e)
	case *Paren:
		return g.simpleStmt(e.X)
	}
	return g.expr(x)
}

func (g *goGen) forStmt(d *ForStmt) {
	init, post := "", ""
	var loopVar *Symbol
	if d.Init != nil {
		switch i := d.Init.(type) {
		case *VarDecl:
			loopVar = i.Pat.Sym
			v := g.zero(loopVar.Type)
			if i.Init != nil {
				v = g.conv(i.Init, loopVar.Type)
			}
			if isNumber(loopVar.Type) {
				v = "float64(" + v + ")" // 字面量 0 会被 Go 推成 int
			}
			init = loopVar.Go + " := " + v
		case *ExprStmt:
			init = g.simpleStmt(i.X)
		}
	}
	cond := ""
	if d.Cond != nil {
		cond = g.truthy(d.Cond)
	}
	if d.Update != nil {
		post = g.simpleStmt(d.Update)
	}
	g.line("for %s; %s; %s {", init, cond, post)
	if loopVar != nil {
		g.ind++
		g.line("_ = %s", loopVar.Go)
		g.ind--
	}
	g.block(d.Body)
	g.line("}")
}

// switchStmt: JS 的 switch 默认贯穿, Go 默认不贯穿 —— 空 case 合并成 case a, b:, 没有 break/return 结尾的补 fallthrough
func (g *goGen) switchStmt(d *SwitchStmt) {
	dt := d.Disc.T()
	g.line("switch %s {", g.expr(d.Disc))
	var pending []string
	hasDefault := false
	for idx, cs := range d.Cases {
		last := idx == len(d.Cases)-1
		if cs.Test == nil {
			hasDefault = true
		} else {
			pending = append(pending, g.conv(cs.Test, unopt(dt)))
		}
		if len(cs.Body) == 0 && !last {
			continue // 空 case: 与下一个合并
		}
		if hasDefault {
			g.line("default:")
		} else {
			g.line("case %s:", strings.Join(pending, ", "))
		}
		pending, hasDefault = nil, false
		body := cs.Body
		jump := false
		if n := len(body); n > 0 {
			switch body[n-1].(type) {
			case *BreakStmt:
				body = body[:n-1] // Go 的 case 自带 break
				jump = true
			case *ReturnStmt, *ThrowStmt, *ContinueStmt:
				jump = true
			}
		}
		g.ind++
		g.stmts(body)
		if !jump && !last {
			g.line("fallthrough")
		}
		g.ind--
	}
	g.line("}")
}

// assign: x = v / x += v, 目标可以是变量 / 字段 / Record 键 / 数组下标
func (g *goGen) assign(e *Assign) string {
	lhs, goType := g.lvalue(e.Target)
	if e.Op == "=" {
		v := g.conv(e.Val, e.Target.T())
		if numConv(goType) {
			v = goType + "(" + v + ")"
		}
		return lhs + " = " + v
	}
	op := strings.TrimSuffix(e.Op, "=")
	if numConv(goType) { // 宿主的 int 字段: 转成 float64 算再转回去
		return fmt.Sprintf("%s = %s(float64(%s) %s (%s))", lhs, goType, lhs, op, g.expr(e.Val))
	}
	if op == "%" {
		return fmt.Sprintf("%s = gotsx.Mod(%s, %s)", lhs, lhs, g.expr(e.Val))
	}
	if op == "+" && isString(e.Target.T()) {
		return lhs + " += " + g.strOf(e.Val)
	}
	return lhs + " " + e.Op + " " + g.expr(e.Val)
}

// update: x++ / x-- 作为语句
func (g *goGen) update(e *Update) string {
	lhs, goType := g.lvalue(e.X)
	if numConv(goType) {
		return fmt.Sprintf("%s = %s(float64(%s) %s 1)", lhs, goType, lhs, string(e.Op[0]))
	}
	return lhs + e.Op
}

// lvalue: 可赋值位置的 Go 表达式 + 宿主字段的原始 Go 类型(数值转换用)
func (g *goGen) lvalue(e Expr) (string, string) {
	switch x := e.(type) {
	case *Paren:
		return g.lvalue(x.X)
	case *Ident:
		return g.ident(x), ""
	case *Member:
		switch t := unopt(x.X.T()).(type) {
		case *ObjT:
			if f := t.Field(x.Name); f != nil {
				return g.expr(x.X) + "." + f.Go, f.GoType
			}
		case *MapT:
			return g.expr(x.X) + "[" + strconv.Quote(x.Name) + "]", ""
		}
	case *Index:
		switch unopt(x.X.T()).(type) {
		case *ArrT:
			return g.expr(x.X) + "[int(" + g.expr(x.I) + ")]", ""
		case *MapT:
			return g.expr(x.X) + "[" + g.expr(x.I) + "]", ""
		}
	}
	g.fail(e.GetPos(), "Go backend: cannot assign to this expression")
	return "", ""
}

// addr: push/pop/splice 需要数组的地址(&xs)
func (g *goGen) addr(e Expr) string {
	switch x := e.(type) {
	case *Paren:
		return g.addr(x.X)
	case *Ident:
		return "&" + g.ident(x)
	case *Member:
		if t, ok := unopt(x.X.T()).(*ObjT); ok {
			if f := t.Field(x.Name); f != nil {
				if numConvSlice(f.GoType) {
					g.fail(x.Pos, "a host numeric-array field is a converted copy and cannot be mutated in place; copy it into a variable first")
				}
				return "&" + g.expr(x.X) + "." + f.Go
			}
		}
		if _, ok := unopt(x.X.T()).(*MapT); ok {
			g.fail(x.Pos, "an array inside a Record cannot be mutated in place (Go map elements are not addressable); read it into a variable first")
		}
	case *Index:
		if _, ok := unopt(x.X.T()).(*ArrT); ok {
			return "&" + g.expr(x.X) + "[int(" + g.expr(x.I) + ")]"
		}
		g.fail(x.Pos, "an array inside a Record cannot be mutated in place (Go map elements are not addressable); read it into a variable first")
	}
	g.fail(e.GetPos(), "in-place mutation needs a variable / field / index")
	return ""
}

var clientOnlyGlobals = map[string]bool{"fetch": true, "setTimeout": true, "clearTimeout": true, "setInterval": true, "clearInterval": true,
	"emit": true, "on": true, "alert": true, "confirm": true, "requestAnimationFrame": true}

// clientOnly: 表达式/语句里是否用到了只有浏览器才有的东西(document、localStorage、fetch、await…)
func clientOnly(n any) bool {
	found := false
	var walkS func(s Stmt)
	var walkE func(e Expr)
	walkE = func(e Expr) {
		walkExpr(e, func(x Expr) bool {
			if found {
				return false
			}
			switch y := x.(type) {
			case *AwaitExpr:
				found = true
			case *Ident:
				if y.Sym != nil && y.Sym.Kind == SBuiltin && (y.Sym.Type == TAny || clientOnlyGlobals[y.Sym.Name]) {
					found = true
				}
			case *Call:
				if y.Kind == "storeSet" {
					found = true
				}
			case *Arrow:
				if y.Body != nil {
					for _, s := range y.Body.Stmts {
						walkS(s)
					}
				}
			}
			return !found
		})
	}
	walkS = func(s Stmt) {
		if found || s == nil {
			return
		}
		switch d := s.(type) {
		case *VarDecl:
			walkE(d.Init)
		case *ReturnStmt:
			walkE(d.X)
		case *ExprStmt:
			walkE(d.X)
		case *ThrowStmt:
			walkE(d.X)
		case *IfStmt:
			walkE(d.Cond)
			walkS(d.Then)
			walkS(d.Else)
		case *ForOfStmt:
			walkE(d.Iter)
			walkS(d.Body)
		case *ForStmt:
			walkS(d.Init)
			walkE(d.Cond)
			walkE(d.Update)
			walkS(d.Body)
		case *WhileStmt:
			walkE(d.Cond)
			walkS(d.Body)
		case *SwitchStmt:
			walkE(d.Disc)
			for _, cs := range d.Cases {
				walkE(cs.Test)
				for _, x := range cs.Body {
					walkS(x)
				}
			}
		case *Block:
			for _, x := range d.Stmts {
				walkS(x)
			}
		case *TryStmt:
			walkS(d.Body)
			walkS(d.Catch)
			walkS(d.Finally)
		case *FuncDecl:
			if d.Async {
				found = true
			} else {
				walkS(d.Body)
			}
		}
	}
	switch x := n.(type) {
	case Expr:
		walkE(x)
	case Stmt:
		walkS(x)
	case []Stmt:
		for _, s := range x {
			walkS(s)
		}
	}
	return found
}

// readsStore: does a module-level helper read a store (cart.count / const { count } = cart)? On the server only
// components carry the render context that holds the request's seed, so such a helper is browser-only (Go gets
// no definition: calling it during a render fails at go build with the .tsx line, like a DOM helper).
func readsStore(stmts []Stmt) bool {
	found := false
	var walkS func(s Stmt)
	walkE := func(e Expr) {
		walkExpr(e, func(x Expr) bool {
			if found {
				return false
			}
			switch y := x.(type) {
			case *Member:
				if _, ok := y.X.T().(*StoreT); ok && y.Name != "set" {
					found = true
				}
			case *Arrow:
				if y.Body != nil {
					for _, s := range y.Body.Stmts {
						walkS(s)
					}
				}
			}
			return !found
		})
	}
	walkS = func(s Stmt) {
		if found || s == nil {
			return
		}
		switch d := s.(type) {
		case *VarDecl:
			if d.Init != nil && d.Pat.Kind == PatObject {
				if _, isStore := d.Init.T().(*StoreT); isStore { // const { count } = cart
					found = true
					return
				}
			}
			walkE(d.Init)
		case *ReturnStmt:
			walkE(d.X)
		case *ExprStmt:
			walkE(d.X)
		case *ThrowStmt:
			walkE(d.X)
		case *IfStmt:
			walkE(d.Cond)
			walkS(d.Then)
			walkS(d.Else)
		case *ForOfStmt:
			walkE(d.Iter)
			walkS(d.Body)
		case *ForStmt:
			walkS(d.Init)
			walkE(d.Cond)
			walkE(d.Update)
			walkS(d.Body)
		case *WhileStmt:
			walkE(d.Cond)
			walkS(d.Body)
		case *SwitchStmt:
			walkE(d.Disc)
			for _, cs := range d.Cases {
				walkE(cs.Test)
				for _, x := range cs.Body {
					walkS(x)
				}
			}
		case *Block:
			for _, x := range d.Stmts {
				walkS(x)
			}
		case *TryStmt:
			walkS(d.Body)
			walkS(d.Catch)
			walkS(d.Finally)
		case *FuncDecl:
			walkS(d.Body)
		}
	}
	for _, s := range stmts {
		walkS(s)
	}
	return found
}

func (g *goGen) stub(ft *FnT, params []string) string {
	body := "{}"
	if ft.Ret != nil && ft.Ret != TVoid && !ft.Async {
		body = "{ return " + g.zero(ft.Ret) + " }"
	}
	ret := ""
	if !ft.Async {
		ret = g.goType(ft.Ret)
	}
	return "func(" + strings.Join(params, ", ") + ") " + ret + " " + body
}

func containsAwait(e Expr) bool {
	found := false
	walkExpr(e, func(x Expr) bool {
		if _, ok := x.(*AwaitExpr); ok {
			found = true
		}
		_, isArrow := x.(*Arrow)
		return !isArrow && !found
	})
	return found
}

func (g *goGen) varDecl(d *VarDecl) {
	switch d.Hook {
	case "useState":
		call := d.Init.(*Call)
		n, set := d.Pat.Elems[0].Sym, d.Pat.Elems[1].Sym
		g.line("var %s %s = %s", n.Go, g.goType(d.Pat.T), g.conv(call.Args[0], d.Pat.T))
		g.line("_ = %s", n.Go)
		g.line("%s := func(any) {}", set.Go)
		g.line("_ = %s", set.Go)
		return
	case "memo":
		if call, ok := d.Init.(*Call); ok && call.Kind == "hook:useMemo" {
			g.line("var %s %s = (%s)()", d.Pat.Sym.Go, g.goType(d.Pat.T), g.expr(call.Args[0]))
			g.line("_ = %s", d.Pat.Sym.Go)
			return
		}
	}
	if d.Pat.Kind == PatIdent {
		sym := d.Pat.Sym
		gt := g.goType(sym.Type)
		if d.Init == nil {
			g.line("var %s %s", sym.Go, gt)
		} else if containsAwait(d.Init) {
			g.line("var %s %s", sym.Go, gt)
		} else if isNode(sym.Type) {
			g.line("var %s gotsx.Node = %s", sym.Go, g.toNode(d.Init, false))
		} else {
			g.line("var %s %s = %s", sym.Go, gt, g.conv(d.Init, sym.Type))
		}
		g.line("_ = %s", sym.Go)
		return
	}
	tmp := g.newTmp()
	if st, ok := d.Init.T().(*StoreT); ok { // const { count } = cart: the request's value of the store
		g.line("%s := %s.Get(_ctx)", tmp, g.expr(d.Init))
		g.line("_ = %s", tmp)
		g.bindParam(d.Pat, tmp, st.State)
		return
	}
	g.line("%s := %s", tmp, g.expr(d.Init))
	g.line("_ = %s", tmp)
	g.bindParam(d.Pat, tmp, d.Init.T())
}

// ---------- 表达式 ----------

// conv: 表达式转成期望类型的 Go 表达式
func (g *goGen) conv(e Expr, want Type) string {
	if _, ok := e.(*NullLit); ok && want != nil {
		return g.zero(want)
	}
	if want != nil && isNode(want) {
		return g.toNode(e, false)
	}
	if want != nil && isString(want) && isNumber(e.T()) {
		return "gotsx.Num(" + g.expr(e) + ")"
	}
	return g.expr(e)
}

func (g *goGen) strOf(e Expr) string {
	t := unopt(e.T())
	switch {
	case isString(t):
		return g.expr(e)
	case isNumber(t):
		return "gotsx.Num(" + g.expr(e) + ")"
	}
	return "gotsx.Str(" + g.expr(e) + ")"
}

func (g *goGen) truthy(e Expr) string {
	if p, ok := e.(*Paren); ok {
		return g.truthy(p.X)
	}
	if u, ok := e.(*Unary); ok && u.Op == "!" {
		return "!(" + g.truthy(u.X) + ")"
	}
	if o, ok := e.T().(*OptT); ok { // 可能缺席的对象(如 find 的结果): 零值即 undefined
		if _, isObj := o.Elem.(*ObjT); isObj {
			return "gotsx.NonZero(" + g.expr(e) + ")"
		}
	}
	t := unopt(e.T())
	switch x := t.(type) {
	case *Prim:
		switch x {
		case TBool:
			return g.expr(e)
		case TString:
			return "(" + g.expr(e) + ` != "")`
		case TNumber:
			return "(" + g.expr(e) + " != 0)"
		case TNode:
			return "(" + g.expr(e) + " != nil)"
		case TUndef:
			return "false"
		}
	case *ArrT, *ObjT, *MapT, *FnT:
		return "true"
	}
	return "gotsx.Truthy(" + g.expr(e) + ")"
}

func (g *goGen) expr(e Expr) string {
	switch x := e.(type) {
	case *Ident:
		return g.ident(x)
	case *NumLit:
		return x.Raw
	case *StrLit:
		return strconv.Quote(x.Val)
	case *BoolLit:
		if x.Val {
			return "true"
		}
		return "false"
	case *RegexLit:
		return "gotsx.Re(" + strconv.Quote(goRegex(x.Pattern, x.Flags)) + ", " + strconv.Quote(x.Flags) + ")"
	case *NullLit:
		return "nil"
	case *TemplateLit:
		var parts []string
		for i, q := range x.Quasis {
			if q != "" {
				parts = append(parts, strconv.Quote(q))
			}
			if i < len(x.Exprs) {
				parts = append(parts, g.strOf(x.Exprs[i]))
			}
		}
		if len(parts) == 0 {
			return `""`
		}
		return strings.Join(parts, " + ")
	case *ArrayLit:
		return g.arrayLit(x)
	case *ObjectLit:
		if mt, ok := unopt(x.T()).(*MapT); ok {
			var fs []string
			for _, p := range x.Props {
				if p.Spread != nil {
					g.fail(x.Pos, "Go backend: object spread is not supported")
				}
				fs = append(fs, strconv.Quote(p.Key)+": "+g.conv(p.Val, mt.Val))
			}
			return "map[string]" + g.goType(mt.Val) + "{" + strings.Join(fs, ", ") + "}"
		}
		o, ok := unopt(x.T()).(*ObjT)
		if !ok {
			g.fail(x.Pos, "cannot determine the type of the object literal")
		}
		var fs []string
		for _, p := range x.Props {
			if p.Spread != nil {
				g.fail(x.Pos, "Go backend: object spread is not supported")
			}
			f := o.Field(p.Key)
			fs = append(fs, f.Go+": "+g.conv(p.Val, f.Type))
		}
		return o.GoName + "{" + strings.Join(fs, ", ") + "}"
	case *Member:
		return g.member(x)
	case *Index:
		xt := unopt(x.X.T())
		switch xt.(type) {
		case *ArrT:
			return "gotsx.At(" + g.expr(x.X) + ", " + g.expr(x.I) + ")" // JS 语义: 越界零值
		case *MapT:
			return g.expr(x.X) + "[" + g.expr(x.I) + "]"
		}
		if isString(xt) {
			return "gotsx.CharAt(" + g.expr(x.X) + ", " + g.expr(x.I) + ")"
		}
		g.fail(x.Pos, "Go backend: cannot index into %s", xt)
	case *Call:
		return g.call(x)
	case *Unary:
		switch x.Op {
		case "!":
			return "!(" + g.truthy(x.X) + ")"
		case "-", "+":
			return x.Op + g.expr(x.X)
		case "delete":
			return "func() bool { " + g.deleteKey(x) + "; return true }()"
		}
		g.fail(x.Pos, "Go backend: %s is not supported", x.Op)
	case *Binary:
		return g.binary(x)
	case *CondExpr:
		t := x.T()
		if isNode(t) {
			s := fmt.Sprintf("func() gotsx.Node { if %s { return %s }; return %s }()", g.truthy(x.Test), g.toNode(x.Then, false), g.toNode(x.Else, false))
			if x.Reactive {
				return "gotsx.Marked(" + s + ")"
			}
			return s
		}
		return fmt.Sprintf("func() %s { if %s { return %s }; return %s }()", g.goType(t), g.truthy(x.Test), g.conv(x.Then, t), g.conv(x.Else, t))
	case *Arrow:
		return g.arrow(x)
	case *Assign:
		g.fail(x.Pos, "Go backend: assignment in expression position is not supported")
	case *Update:
		id, ok := x.X.(*Ident)
		if !ok {
			g.fail(x.Pos, "%s as an expression only works on a variable (or write it as a standalone statement)", x.Op)
		}
		name := g.ident(id)
		if x.Prefix {
			return fmt.Sprintf("func() float64 { %s%s; return %s }()", name, x.Op, name)
		}
		return fmt.Sprintf("func() float64 { v := %s; %s%s; return v }()", name, name, x.Op)
	case *AsExpr:
		return g.expr(x.X)
	case *AwaitExpr:
		g.fail(x.Pos, "await can only be used in client code")
	case *NonNull:
		return g.expr(x.X)
	case *Paren:
		return "(" + g.expr(x.X) + ")"
	case *JSXElem, *JSXFrag:
		return g.toNode(e, false)
	case *SpreadExpr:
		return g.expr(x.X)
	}
	g.fail(e.GetPos(), "Go backend: unsupported expression %T", e)
	return ""
}

func (g *goGen) ident(x *Ident) string {
	s := x.Sym
	if s == nil {
		g.fail(x.Pos, "unresolved identifier %s", x.Name)
	}
	switch s.Kind {
	case SHostMember:
		g.needHost = true
		return s.Go
	case SComp:
		g.fail(x.Pos, "component %s cannot be used as a value", x.Name)
	case SBuiltin:
		g.fail(x.Pos, "%s can only be used in client code", x.Name)
	}
	return s.Go
}

func (g *goGen) arrayLit(x *ArrayLit) string {
	at, ok := unopt(x.T()).(*ArrT)
	if !ok {
		g.fail(x.Pos, "cannot determine the array type")
	}
	et := g.goType(at.Elem)
	var parts []string
	var cur []string
	flush := func() {
		if len(cur) > 0 {
			parts = append(parts, "[]"+et+"{"+strings.Join(cur, ", ")+"}")
			cur = nil
		}
	}
	for _, el := range x.Elems {
		if sp, ok := el.(*SpreadExpr); ok {
			flush()
			parts = append(parts, g.expr(sp.X))
			continue
		}
		cur = append(cur, g.conv(el, at.Elem))
	}
	flush()
	if len(parts) == 0 {
		return "[]" + et + "{}"
	}
	out := parts[0]
	for _, p := range parts[1:] {
		out = "gotsx.Concat(" + out + ", " + p + ")"
	}
	return out
}

func (g *goGen) member(x *Member) string {
	xt := unopt(x.X.T())
	switch t := xt.(type) {
	case *ArrT:
		if x.Name == "length" {
			return "float64(len(" + g.expr(x.X) + "))"
		}
	case *Prim:
		if t == TString && x.Name == "length" {
			return "gotsx.StrLen(" + g.expr(x.X) + ")"
		}
	case *ObjT:
		f := t.Field(x.Name)
		if f != nil {
			s := g.expr(x.X) + "." + f.Go
			if numConv(f.GoType) {
				return "float64(" + s + ")"
			}
			if numConvSlice(f.GoType) {
				return "gotsx.Nums(" + s + ")"
			}
			return s
		}
		return g.expr(x.X) + "." + x.GoName // 宿主方法, 由 call 处理
	case *MapT:
		return g.expr(x.X) + "[" + strconv.Quote(x.Name) + "]"
	case *HostModT:
		g.needHost = true
		return t.Go + "." + x.GoName
	case *StoreT:
		if x.Name == "set" {
			g.fail(x.Pos, "%s.set can only be used in client code", t.Sym.Name)
		}
		f := t.State.Field(x.Name)
		s := g.expr(x.X) + ".Get(_ctx)." + f.Go
		if numConv(f.GoType) {
			return "float64(" + s + ")"
		}
		if numConvSlice(f.GoType) {
			return "gotsx.Nums(" + s + ")"
		}
		return s
	}
	g.fail(x.Pos, "Go backend: %s has no accessible member %s", xt, x.Name)
	return ""
}

func (g *goGen) call(x *Call) string {
	switch {
	case x.Kind == "host":
		return g.hostCall(x, false)
	case strings.HasPrefix(x.Kind, "builtin:"):
		return g.builtinCall(x)
	case strings.HasPrefix(x.Kind, "global:"):
		name := strings.TrimPrefix(x.Kind, "global:")
		arg := func() string { return g.expr(x.Args[0]) }
		switch name {
		case "String":
			return "gotsx.Str(" + arg() + ")"
		case "Number", "parseInt", "parseFloat":
			return "gotsx.ToNum(" + arg() + ")"
		case "Boolean":
			return g.truthy(x.Args[0])
		case "encodeURIComponent":
			return "gotsx.EncodeURIComponent(" + arg() + ")"
		case "decodeURIComponent":
			return "gotsx.DecodeURIComponent(" + arg() + ")"
		case "isNaN":
			return "gotsx.IsNaN(" + arg() + ")"
		case "jsonLd":
			return "gotsx.LdScript(" + arg() + ")"
		case "t":
			return "gotsx.Tr(" + g.expr(x.Args[0]) + ", " + g.expr(x.Args[1]) + ")"
		case "tv":
			return "gotsx.Trv(" + g.expr(x.Args[0]) + ", " + g.expr(x.Args[1]) + ", " + g.expr(x.Args[2]) + ")"
		case "plural":
			return "gotsx.Plural(" + g.expr(x.Args[0]) + ", " + g.expr(x.Args[1]) + ", " + g.expr(x.Args[2]) + ")"
		case "fmtNum":
			return "gotsx.FmtNum(" + g.expr(x.Args[0]) + ", " + g.expr(x.Args[1]) + ")"
		case "fmtCur":
			return "gotsx.FmtCur(" + g.expr(x.Args[0]) + ", " + g.expr(x.Args[1]) + ")"
		case "fmtDate":
			return "gotsx.FmtDate(" + g.expr(x.Args[0]) + ", " + g.expr(x.Args[1]) + ")"
		case "lpath":
			return "gotsx.LPath(" + g.expr(x.Args[0]) + ", " + g.expr(x.Args[1]) + ")"
		case "isoDate":
			return "gotsx.IsoDate(" + arg() + ")"
		case "redirect":
			code := "302"
			if len(x.Args) == 2 {
				code = g.expr(x.Args[1])
			}
			return "gotsx.Redirect(" + arg() + ", " + code + ")"
		case "notFound":
			return "gotsx.NotFound()"
		case "seed":
			st := x.Args[0].T().(*StoreT)
			return "gotsx.Seed(props, " + g.expr(x.Args[0]) + ", " + g.conv(x.Args[1], st.State) + ")"
		}
		g.fail(x.Pos, "%s can only be used in client code", name)
	case x.Kind == "storeSet":
		g.fail(x.Pos, "store.set can only be used in client code (an event handler, effect or plain function)")
	case x.Kind == "setter":
		return g.expr(x.Fn) + "(" + g.expr(x.Args[0]) + ")"
	case x.Kind == "hook:useMemo":
		return "(" + g.expr(x.Args[0]) + ")()"
	case x.Kind == "fn":
		ft, _ := unopt(x.Fn.T()).(*FnT)
		var args []string
		for i, a := range x.Args {
			var want Type
			if ft != nil && i < len(ft.Params) {
				want = ft.Params[i].Type
			}
			args = append(args, g.conv(a, want))
		}
		return g.expr(x.Fn) + "(" + strings.Join(args, ", ") + ")"
	}
	g.fail(x.Pos, "Go backend: cannot compile this call (%s)", x.Kind)
	return ""
}

func (g *goGen) hostCall(x *Call, stmt bool) string {
	m := x.Host
	var callee string
	switch f := x.Fn.(type) {
	case *Ident:
		callee = g.ident(f)
	case *Member:
		callee = g.member(f)
	default:
		g.fail(x.Pos, "unsupported host call form")
	}
	g.needHost = true
	var args []string
	for i, a := range x.Args {
		s := g.conv(a, m.Params[i].Type)
		if numConv(m.Params[i].Go) {
			s = m.Params[i].Go + "(" + s + ")"
		}
		args = append(args, s)
	}
	call := callee + "(" + strings.Join(args, ", ") + ")"
	if stmt {
		return call
	}
	if m.Throws {
		call = "gotsx.Must(" + call + ")"
	}
	if numConv(m.GoRet) {
		call = "float64(" + call + ")"
	}
	if numConvSlice(m.GoRet) {
		call = "gotsx.Nums(" + call + ")"
	}
	return call
}

func (g *goGen) builtinCall(x *Call) string {
	name := strings.TrimPrefix(x.Kind, "builtin:")
	mem := x.Fn.(*Member)
	recv := ""
	if _, isGlobal := unopt(mem.X.T()).(*GlobalT); !isGlobal {
		recv = g.expr(mem.X) // console/JSON/Math 是命名空间, 不能当值求值
	}
	arg := func(i int) string {
		if i < len(x.Args) {
			return g.expr(x.Args[i])
		}
		return ""
	}
	rt := unopt(mem.X.T())
	switch r := rt.(type) {
	case *ArrT:
		switch name {
		case "map":
			if a, ok := x.Args[0].(*Arrow); ok && len(a.Params) == 2 {
				return "gotsx.MapI(" + recv + ", " + g.expr(x.Args[0]) + ")"
			}
			if a, ok := x.Args[0].(*Arrow); ok && len(a.Params) == 0 {
				ret := "gotsx.Node"
				if at, ok := unopt(x.T()).(*ArrT); ok {
					ret = g.goType(at.Elem)
				}
				return "gotsx.Map(" + recv + ", func(_ " + g.goType(r.Elem) + ") " + ret + " { return (" + g.expr(x.Args[0]) + ")() })"
			}
			return "gotsx.Map(" + recv + ", " + g.expr(x.Args[0]) + ")"
		case "filter", "find", "some", "every", "forEach", "findIndex":
			suffix := ""
			if a, ok := x.Args[0].(*Arrow); ok && len(a.Params) == 2 {
				suffix = "I"
			}
			return "gotsx." + strings.ToUpper(name[:1]) + name[1:] + suffix + "(" + recv + ", " + arg(0) + ")"
		case "lastIndexOf":
			return "gotsx.LastIndexOf(" + recv + ", " + g.conv(x.Args[0], r.Elem) + ")"
		case "push", "unshift":
			var as []string
			for _, a := range x.Args {
				as = append(as, g.conv(a, r.Elem))
			}
			return "gotsx." + strings.ToUpper(name[:1]) + name[1:] + "(" + g.addr(mem.X) + ", " + strings.Join(as, ", ") + ")"
		case "pop", "shift":
			return "gotsx." + strings.ToUpper(name[:1]) + name[1:] + "(" + g.addr(mem.X) + ")"
		case "splice":
			del := "-1" // 省略 deleteCount = 删到末尾
			if len(x.Args) > 1 {
				del = arg(1)
			}
			as := []string{g.addr(mem.X), arg(0), del}
			if len(x.Args) > 2 {
				for _, a := range x.Args[2:] {
					as = append(as, g.conv(a, r.Elem))
				}
			}
			return "gotsx.Splice(" + strings.Join(as, ", ") + ")"
		case "includes":
			return "gotsx.Includes(" + recv + ", " + g.conv(x.Args[0], r.Elem) + ")"
		case "indexOf":
			return "gotsx.IndexOf(" + recv + ", " + g.conv(x.Args[0], r.Elem) + ")"
		case "join":
			sep := `","`
			if len(x.Args) > 0 {
				sep = arg(0)
			}
			if isString(r.Elem) {
				return "gotsx.Join(" + recv + ", " + sep + ")"
			}
			return "gotsx.JoinAny(" + recv + ", " + sep + ")"
		case "slice":
			as := []string{"0"} // xs.slice() = 浅拷贝
			if len(x.Args) > 0 {
				as = nil
				for i := range x.Args {
					as = append(as, arg(i))
				}
			}
			return "gotsx.Slice(" + strings.Join(append([]string{recv}, as...), ", ") + ")"
		case "concat":
			return "gotsx.Concat(" + recv + ", " + arg(0) + ")"
		case "reverse":
			return "gotsx.Reverse(" + recv + ")"
		case "at":
			return "gotsx.AtWrap(" + recv + ", " + arg(0) + ")"
		case "flat":
			return "gotsx.Flat(" + recv + ")"
		case "sort":
			return "gotsx.Sort(" + recv + ", " + arg(0) + ")"
		case "reduce":
			return "gotsx.Reduce(" + recv + ", " + arg(0) + ", " + arg(1) + ")"
		}
	case *Prim:
		if r == TRegExp && name == "test" {
			return "gotsx.ReTest(" + recv + ", " + arg(0) + ")"
		}
		if r == TString {
			switch name {
			case "re_replace", "re_replaceAll":
				return "gotsx.ReReplace(" + recv + ", " + arg(0) + ", " + arg(1) + ")"
			case "re_split":
				return "gotsx.ReSplit(" + recv + ", " + arg(0) + ")"
			case "re_match":
				return "gotsx.ReMatch(" + recv + ", " + arg(0) + ")"
			case "re_search":
				return "gotsx.ReSearch(" + recv + ", " + arg(0) + ")"
			}
			switch name {
			case "toUpperCase":
				return "gotsx.Upper(" + recv + ")"
			case "toLowerCase":
				return "gotsx.Lower(" + recv + ")"
			case "trim":
				return "gotsx.Trim(" + recv + ")"
			case "trimStart":
				return "gotsx.TrimStart(" + recv + ")"
			case "trimEnd":
				return "gotsx.TrimEnd(" + recv + ")"
			case "lastIndexOf":
				return "gotsx.StrLastIndexOf(" + recv + ", " + arg(0) + ")"
			case "localeCompare":
				return "gotsx.Compare(" + recv + ", " + arg(0) + ")"
			case "toString":
				return recv
			case "at":
				return "gotsx.StrAt(" + recv + ", " + arg(0) + ")"
			case "includes":
				return "gotsx.StrIncludes(" + recv + ", " + arg(0) + ")"
			case "startsWith":
				return "gotsx.StartsWith(" + recv + ", " + arg(0) + ")"
			case "endsWith":
				return "gotsx.EndsWith(" + recv + ", " + arg(0) + ")"
			case "split":
				return "gotsx.Split(" + recv + ", " + arg(0) + ")"
			case "slice":
				as := []string{"0"}
				if len(x.Args) > 0 {
					as = nil
					for i := range x.Args {
						as = append(as, arg(i))
					}
				}
				return "gotsx.StrSlice(" + strings.Join(append([]string{recv}, as...), ", ") + ")"
			case "replace":
				return "gotsx.Replace(" + recv + ", " + arg(0) + ", " + arg(1) + ")"
			case "replaceAll":
				return "gotsx.ReplaceAll(" + recv + ", " + arg(0) + ", " + arg(1) + ")"
			case "repeat":
				return "gotsx.Repeat(" + recv + ", " + arg(0) + ")"
			case "indexOf":
				return "gotsx.StrIndexOf(" + recv + ", " + arg(0) + ")"
			case "charAt":
				return "gotsx.CharAt(" + recv + ", " + arg(0) + ")"
			case "padStart":
				p := `" "`
				if len(x.Args) > 1 {
					p = arg(1)
				}
				return "gotsx.PadStart(" + recv + ", " + arg(0) + ", " + p + ")"
			case "padEnd":
				p := `" "`
				if len(x.Args) > 1 {
					p = arg(1)
				}
				return "gotsx.PadEnd(" + recv + ", " + arg(0) + ", " + p + ")"
			}
		}
		if r == TNumber && name == "toString" {
			return "gotsx.Num(" + recv + ")"
		}
		if r == TNumber && name == "toFixed" {
			d := "0"
			if len(x.Args) > 0 {
				d = arg(0)
			}
			return "gotsx.ToFixed(" + recv + ", " + d + ")"
		}
	case *GlobalT:
		var args []string
		for i := range x.Args {
			args = append(args, arg(i))
		}
		switch r.Name {
		case "console":
			return "gotsx.Log(" + strings.Join(args, ", ") + ")"
		case "JSON":
			if name == "stringify" {
				return "gotsx.JSON(" + arg(0) + ")"
			}
		case "Math":
			switch name {
			case "max", "min", "floor", "ceil", "round", "abs":
				return "gotsx." + strings.ToUpper(name[:1]) + name[1:] + "(" + strings.Join(args, ", ") + ")"
			case "random":
				return "gotsx.Random()"
			case "sqrt":
				return "gotsx.Sqrt(" + arg(0) + ")"
			case "pow":
				return "gotsx.Pow(" + arg(0) + ", " + arg(1) + ")"
			case "sign":
				return "gotsx.Sign(" + arg(0) + ")"
			case "trunc":
				return "gotsx.Trunc(" + arg(0) + ")"
			}
		case "Date":
			switch name {
			case "now":
				return "gotsx.Now()"
			case "parse":
				return "gotsx.DateParse(" + arg(0) + ")"
			}
		case "Object":
			switch name {
			case "keys":
				return "gotsx.ObjectKeys(" + arg(0) + ")"
			case "values":
				return "gotsx.ObjectValues(" + arg(0) + ")"
			case "hasOwn":
				return "gotsx.HasKey(" + arg(0) + ", " + arg(1) + ")"
			}
		}
	}
	g.fail(x.Pos, "Go backend: %s.%s is not supported", rt, name)
	return ""
}

func (g *goGen) binary(x *Binary) string {
	t := x.T()
	switch x.Op {
	case "&&":
		if isNode(t) {
			fn := "gotsx.IfPlain"
			if x.Reactive {
				fn = "gotsx.If"
			}
			return fn + "(" + g.truthy(x.L) + ", func() gotsx.Node { return " + g.toNode(x.R, false) + " })"
		}
		if isBool(t) {
			return "(" + g.truthy(x.L) + " && " + g.truthy(x.R) + ")"
		}
		return fmt.Sprintf("func() %s { if !(%s) { return %s }; return %s }()", g.goType(t), g.truthy(x.L), g.zero(t), g.conv(x.R, t))
	case "||", "??":
		switch {
		case isString(t):
			return "gotsx.Or(" + g.expr(x.L) + ", " + g.conv(x.R, t) + ")"
		case isNumber(t):
			return "gotsx.OrNum(" + g.expr(x.L) + ", " + g.conv(x.R, t) + ")"
		case isBool(t):
			return "(" + g.truthy(x.L) + " || " + g.truthy(x.R) + ")"
		case isNode(t):
			return fmt.Sprintf("func() gotsx.Node { if l := %s; l != nil { return l }; return %s }()", g.toNode(x.L, false), g.toNode(x.R, false))
		}
		return fmt.Sprintf("func() %s { l := %s; if %s { return l }; return %s }()", g.goType(t), g.expr(x.L), g.truthyOf(x.L.T(), "l"), g.conv(x.R, t))
	case "+":
		if isString(t) {
			return "(" + g.strOf(x.L) + " + " + g.strOf(x.R) + ")"
		}
		return "(" + g.expr(x.L) + " + " + g.expr(x.R) + ")"
	case "-", "*", "/":
		return "(" + g.expr(x.L) + " " + x.Op + " " + g.expr(x.R) + ")"
	case "%":
		return "gotsx.Mod(" + g.expr(x.L) + ", " + g.expr(x.R) + ")"
	case "===", "==":
		if z := g.zeroCheck(x); z != "" {
			return z
		}
		return "(" + g.expr(x.L) + " == " + g.conv(x.R, x.L.T()) + ")"
	case "!==", "!=":
		if z := g.zeroCheck(x); z != "" {
			return "!" + z
		}
		return "(" + g.expr(x.L) + " != " + g.conv(x.R, x.L.T()) + ")"
	default:
		return "(" + g.expr(x.L) + " " + x.Op + " " + g.expr(x.R) + ")"
	}
}

// zeroCheck: obj === undefined / null 对复合类型比较零值(结构体含切片时 == 不能编译)
func (g *goGen) zeroCheck(x *Binary) string {
	other := x.L
	if _, ok := x.L.(*NullLit); ok {
		other = x.R
	} else if _, ok := x.R.(*NullLit); !ok {
		return ""
	}
	switch unopt(other.T()).(type) {
	case *ObjT, *ArrT, *MapT, *FnT:
		return "gotsx.IsZero(" + g.expr(other) + ")"
	}
	return ""
}

func (g *goGen) truthyOf(t Type, v string) string {
	if o, ok := t.(*OptT); ok {
		if _, isObj := o.Elem.(*ObjT); isObj {
			return "gotsx.NonZero(" + v + ")"
		}
	}
	switch unopt(t) {
	case TString:
		return v + ` != ""`
	case TNumber:
		return v + " != 0"
	case TBool:
		return v
	}
	return "gotsx.Truthy(" + v + ")"
}

func (g *goGen) arrow(x *Arrow) string {
	ft, _ := x.T().(*FnT)
	if ft == nil {
		g.fail(x.Pos, "arrow function type is unknown")
	}
	var ps []string
	for i, p := range x.Params {
		name := "p" + strconv.Itoa(i)
		if p.Pat.Kind == PatIdent {
			name = p.Pat.Sym.Go
		}
		ps = append(ps, name+" "+g.goType(ft.Params[i].Type))
	}
	var bodyNode any = x.ExprBody
	if x.Body != nil {
		bodyNode = x.Body.Stmts
	}
	if x.Async || clientOnly(bodyNode) { // 只进 JS 后端; Go 里留一个同类型的空壳
		return g.stub(ft, ps)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "func(%s) %s {\n", strings.Join(ps, ", "), g.goType(ft.Ret))
	sub := &goGen{c: g.c, m: g.m, ind: g.ind + 1, hostPkg: g.hostPkg, tmp: g.tmp, curRet: ft.Ret}
	for i, p := range x.Params {
		if p.Pat.Kind != PatIdent {
			sub.bindParam(p.Pat, "p"+strconv.Itoa(i), ft.Params[i].Type)
		} else {
			sub.line("_ = %s", p.Pat.Sym.Go)
		}
	}
	if x.ExprBody != nil {
		switch {
		case ft.Ret == nil || ft.Ret == TVoid:
			sub.exprStmt(x.ExprBody)
		case isNode(ft.Ret):
			sub.line("return %s", sub.toNode(x.ExprBody, false))
		default:
			sub.line("return %s", sub.conv(x.ExprBody, ft.Ret))
		}
	} else {
		sub.stmts(x.Body.Stmts)
	}
	g.tmp = sub.tmp
	if sub.needHost {
		g.needHost = true
	}
	b.WriteString(sub.b.String())
	b.WriteString(strings.Repeat("\t", g.ind) + "}")
	return b.String()
}

// ---------- JSX ----------

// toNode: 任意子节点表达式 → gotsx.Node 表达式
func (g *goGen) toNode(e Expr, reactive bool) string {
	switch x := e.(type) {
	case *JSXElem:
		return g.jsxElem(x)
	case *JSXFrag:
		return g.childrenNode(x.Children)
	case *JSXText:
		s := normalizeJSXText(x.Text)
		if s == "" {
			return "nil"
		}
		return "gotsx.Text(" + strconv.Quote(s) + ")"
	case *JSXExprChild:
		if x.X == nil {
			return "nil"
		}
		return g.toNode(x.X, x.Reactive)
	case *Paren:
		return g.toNode(x.X, reactive)
	case *NullLit, *BoolLit:
		return "nil"
	}
	t := unopt(e.T())
	switch tt := t.(type) {
	case *Prim:
		switch tt {
		case TNode:
			return g.expr(e)
		case TString:
			if reactive {
				return "gotsx.Dyn(" + g.expr(e) + ")"
			}
			return "gotsx.Text(" + g.expr(e) + ")"
		case TNumber:
			if reactive {
				return "gotsx.Dyn(gotsx.Num(" + g.expr(e) + "))"
			}
			return "gotsx.Text(gotsx.Num(" + g.expr(e) + "))"
		case TBool, TUndef, TVoid:
			return "nil"
		}
		return "gotsx.Text(gotsx.Str(" + g.expr(e) + "))"
	case *ArrT:
		if isNode(tt.Elem) {
			if reactive {
				return "gotsx.Nodes(" + g.expr(e) + ")"
			}
			return "gotsx.NodesPlain(" + g.expr(e) + ")"
		}
		return "gotsx.Text(gotsx.JoinAny(" + g.expr(e) + `, ""))`
	}
	g.fail(e.GetPos(), "cannot use %s as a JSX child", t)
	return ""
}

func (g *goGen) children(kids []Expr) string {
	var out []string
	for _, k := range kids {
		if t, ok := k.(*JSXText); ok && normalizeJSXText(t.Text) == "" {
			continue
		}
		if ec, ok := k.(*JSXExprChild); ok && ec.X == nil {
			continue
		}
		out = append(out, g.toNode(k, false))
	}
	return strings.Join(out, ", ")
}

func (g *goGen) jsxElem(x *JSXElem) string {
	if x.Comp != nil && x.Comp.Go == "gotsx.Suspense" {
		// 边界: fallback 立即求值进外壳, children 包进 thunk —— 里面的宿主调用在外壳发出后才跑
		fb := "nil"
		for _, a := range x.Attrs {
			if a.Name == "fallback" && a.Val != nil {
				fb = g.toNode(a.Val, false)
			}
		}
		return "gotsx.Suspense(" + fb + ", func() gotsx.Node { return " + g.childrenNode(x.Children) + " })"
	}
	if x.Comp != nil {
		comp := x.Comp.Comp
		var fs []string
		for _, a := range x.Attrs {
			if a.Name == "key" {
				continue
			}
			f := comp.Props.Field(a.Name)
			if a.Val == nil {
				fs = append(fs, f.Go+": true")
				continue
			}
			fs = append(fs, f.Go+": "+g.conv(a.Val, f.Type))
		}
		if len(x.Children) > 0 {
			fs = append(fs, "Children: "+g.childrenNode(x.Children))
		}
		ctxArg := ""
		if x.Comp.Module != nil && x.Comp.Module.Kind == "client" && x.Comp != x.Comp.Module.Default { // a helper component of a client module takes the render context (islands wrap it themselves)
			ctxArg = "_ctx, "
		}
		return x.Comp.Go + "(" + ctxArg + comp.Props.GoName + "{" + strings.Join(fs, ", ") + "})"
	}
	w := &htmlWriter{g: g}
	w.elem(x)
	return w.closure()
}

// ---------- 流式写入: 元素编成对 _ctx 的顺序写入, 静态 HTML 合并成一个字符串(templ 的做法), 每个组件只有一个闭包 ----------

var voidTags = map[string]bool{"area": true, "base": true, "br": true, "col": true, "embed": true, "hr": true, "img": true, "input": true, "link": true, "meta": true, "source": true, "track": true, "wbr": true}

type htmlWriter struct {
	g     *goGen
	raw   strings.Builder // 待写出的静态 HTML(编译期已转义)
	stmts []string
}

func (w *htmlWriter) text(s string) { w.raw.WriteString(s) }
func (w *htmlWriter) flush() {
	if w.raw.Len() > 0 {
		w.stmts = append(w.stmts, "_ctx.W("+strconv.Quote(w.raw.String())+")")
		w.raw.Reset()
	}
}
func (w *htmlWriter) stmt(s string) {
	w.flush()
	w.stmts = append(w.stmts, s)
}

// closure: 收尾成一个 gotsx.Node 字面量
func (w *htmlWriter) closure() string {
	w.flush()
	if len(w.stmts) == 0 {
		return "gotsx.Node(nil)"
	}
	ind := strings.Repeat("\t", w.g.ind+1)
	return "func(_ctx *gotsx.Ctx) {\n" + ind + strings.Join(w.stmts, "\n"+ind) + "\n" + strings.Repeat("\t", w.g.ind) + "}"
}

func (w *htmlWriter) elem(x *JSXElem) {
	if x.Comp != nil {
		w.stmt("_ctx.N(" + w.g.jsxElem(x) + ")")
		return
	}
	g := w.g
	w.text("<" + x.Tag)
	for _, a := range x.Attrs {
		if a.Name == "key" || strings.HasPrefix(a.Name, "on") || a.Name == "dangerouslySetInnerHTML" {
			continue
		}
		if a.Val == nil {
			w.text(" " + a.Name)
			continue
		}
		if s, ok := a.Val.(*StrLit); ok {
			w.text(" " + a.Name + `="` + html.EscapeString(s.Val) + `"`)
			continue
		}
		name := strconv.Quote(a.Name)
		vt := unopt(a.Val.T())
		switch {
		case isBool(vt) && (strings.HasPrefix(a.Name, "aria-") || strings.HasPrefix(a.Name, "data-")):
			w.stmt("_ctx.Attr(" + name + ", gotsx.Str(" + g.expr(a.Val) + "))")
		case isBool(vt):
			w.stmt("if " + g.expr(a.Val) + " {\n\t\t_ctx.W(" + strconv.Quote(" "+a.Name) + ")\n\t}")
		case isNumber(vt):
			w.stmt("_ctx.Attr(" + name + ", gotsx.Num(" + g.expr(a.Val) + "))")
		case isString(vt):
			w.stmt("_ctx.Attr(" + name + ", " + g.expr(a.Val) + ")")
		default:
			w.stmt("_ctx.Attr(" + name + ", gotsx.Str(" + g.expr(a.Val) + "))")
		}
	}
	w.text(">")
	if voidTags[x.Tag] {
		return
	}
	w.kids(x.Children)
	if x.Tag == "head" || x.Tag == "body" {
		w.stmt("_ctx.Close(" + strconv.Quote(x.Tag) + ")")
	} else {
		w.text("</" + x.Tag + ">")
	}
}

func (w *htmlWriter) kids(kids []Expr) {
	for _, k := range kids {
		switch x := k.(type) {
		case *JSXText:
			w.text(html.EscapeString(normalizeJSXText(x.Text)))
		case *JSXExprChild:
			if x.X != nil {
				w.child(x.X, x.Reactive)
			}
		default:
			w.child(k, false)
		}
	}
}

// child: 子节点位置的表达式 —— JSX 继续内联, 文本就地转义, 其它节点表达式调用
func (w *htmlWriter) child(e Expr, reactive bool) {
	g := w.g
	for {
		p, ok := e.(*Paren)
		if !ok {
			break
		}
		e = p.X
	}
	switch x := e.(type) {
	case *JSXElem:
		w.elem(x)
		return
	case *JSXFrag:
		w.kids(x.Children)
		return
	case *JSXText:
		w.text(html.EscapeString(normalizeJSXText(x.Text)))
		return
	case *NullLit, *BoolLit:
		return
	case *StrLit:
		w.text(html.EscapeString(x.Val))
		return
	}
	if w.inlineMap(e, reactive) {
		return
	}
	t := unopt(e.T())
	switch tt := t.(type) {
	case *Prim:
		switch tt {
		case TNode:
			w.stmt("_ctx.N(" + g.expr(e) + ")")
		case TString:
			if reactive {
				w.stmt("_ctx.Dyn(" + g.expr(e) + ")")
			} else {
				w.stmt("_ctx.Esc(" + g.expr(e) + ")")
			}
		case TNumber:
			if reactive {
				w.stmt("_ctx.Dyn(gotsx.Num(" + g.expr(e) + "))")
			} else {
				w.stmt("_ctx.Esc(gotsx.Num(" + g.expr(e) + "))")
			}
		case TBool, TUndef, TVoid:
		default:
			w.stmt("_ctx.Esc(gotsx.Str(" + g.expr(e) + "))")
		}
		return
	case *ArrT:
		if isNode(tt.Elem) {
			if reactive {
				w.stmt("gotsx.Nodes(" + g.expr(e) + ")(_ctx)")
			} else {
				w.stmt("gotsx.NodesPlain(" + g.expr(e) + ")(_ctx)")
			}
		} else {
			w.stmt("_ctx.Esc(gotsx.JoinAny(" + g.expr(e) + `, ""))`)
		}
		return
	}
	g.fail(e.GetPos(), "cannot use %s as a JSX child", t)
}

// inlineMap: {xs.map((x) => <li>…</li>)} 直接编成 for 循环写入, 不构造 []Node 和每项的闭包。
// 只处理箭头函数是表达式体(或只有一个 return)且参数是普通标识符的情况; 其它走通用路径。
func (w *htmlWriter) inlineMap(e Expr, reactive bool) bool {
	call, ok := e.(*Call)
	if !ok || call.Kind != "builtin:map" || len(call.Args) != 1 {
		return false
	}
	m, ok := call.Fn.(*Member)
	if !ok {
		return false
	}
	if at, ok := unopt(call.T()).(*ArrT); !ok || !isNode(at.Elem) {
		return false
	}
	if _, ok := unopt(m.X.T()).(*ArrT); !ok {
		return false
	}
	a, ok := call.Args[0].(*Arrow)
	if !ok || a.Async || len(a.Params) > 2 {
		return false
	}
	body := a.ExprBody
	if body == nil {
		if a.Body == nil || len(a.Body.Stmts) != 1 {
			return false
		}
		r, ok := a.Body.Stmts[0].(*ReturnStmt)
		if !ok || r.X == nil {
			return false
		}
		body = r.X
	}
	for _, p := range a.Params {
		if p.Pat.Kind != PatIdent {
			return false
		}
	}
	g := w.g
	if reactive {
		w.stmt("_ctx.ListStart()")
	}
	item := "_"
	if len(a.Params) >= 1 {
		item = a.Params[0].Pat.Sym.Go
	}
	switch {
	case len(a.Params) == 2:
		idx := a.Params[1].Pat.Sym.Go
		w.stmt("for _i, " + item + " := range " + g.expr(m.X) + " {")
		w.stmt("\t" + idx + " := float64(_i)")
		w.stmt("\t_ = " + idx)
		w.stmt("\t_ = " + item)
	case len(a.Params) == 1:
		w.stmt("for _, " + item + " := range " + g.expr(m.X) + " {")
		w.stmt("\t_ = " + item)
	default: // () => <Skeleton />: 只按长度重复
		w.stmt("for range " + g.expr(m.X) + " {")
	}
	inner := &htmlWriter{g: g}
	inner.child(body, false)
	inner.flush()
	for _, s := range inner.stmts {
		w.stmt("\t" + s)
	}
	w.stmt("}")
	if reactive {
		w.stmt("_ctx.ListEnd()")
	}
	return true
}

// childrenNode: 一组子节点 → 一个 Node(组件的 children / fragment)
func (g *goGen) childrenNode(kids []Expr) string {
	w := &htmlWriter{g: g}
	w.kids(kids)
	return w.closure()
}

// JSX 文本的空白规则(与 React/Babel 一致): 多行时按行 trim, 空行丢弃, 用单个空格拼接
func normalizeJSXText(s string) string {
	if !strings.Contains(s, "\n") {
		return s
	}
	lines := strings.Split(s, "\n")
	var out []string
	for i, ln := range lines {
		ln = strings.ReplaceAll(ln, "\t", " ")
		if i != 0 {
			ln = strings.TrimLeft(ln, " \r")
		}
		if i != len(lines)-1 {
			ln = strings.TrimRight(ln, " \r")
		}
		if ln != "" {
			out = append(out, ln)
		}
	}
	return strings.Join(out, " ")
}

// walkExpr: 深度优先遍历(f 返回 false 不再深入)
func walkExpr(e Expr, f func(Expr) bool) {
	if e == nil || !f(e) {
		return
	}
	switch x := e.(type) {
	case *TemplateLit:
		for _, a := range x.Exprs {
			walkExpr(a, f)
		}
	case *ArrayLit:
		for _, a := range x.Elems {
			walkExpr(a, f)
		}
	case *ObjectLit:
		for _, p := range x.Props {
			walkExpr(p.Val, f)
			walkExpr(p.Spread, f)
		}
	case *Member:
		walkExpr(x.X, f)
	case *Index:
		walkExpr(x.X, f)
		walkExpr(x.I, f)
	case *Call:
		walkExpr(x.Fn, f)
		for _, a := range x.Args {
			walkExpr(a, f)
		}
	case *Unary:
		walkExpr(x.X, f)
	case *Binary:
		walkExpr(x.L, f)
		walkExpr(x.R, f)
	case *CondExpr:
		walkExpr(x.Test, f)
		walkExpr(x.Then, f)
		walkExpr(x.Else, f)
	case *Arrow:
		walkExpr(x.ExprBody, f)
	case *Assign:
		walkExpr(x.Target, f)
		walkExpr(x.Val, f)
	case *Update:
		walkExpr(x.X, f)
	case *AsExpr:
		walkExpr(x.X, f)
	case *AwaitExpr:
		walkExpr(x.X, f)
	case *SpreadExpr:
		walkExpr(x.X, f)
	case *NonNull:
		walkExpr(x.X, f)
	case *Paren:
		walkExpr(x.X, f)
	case *JSXElem:
		for _, a := range x.Attrs {
			walkExpr(a.Val, f)
		}
		for _, k := range x.Children {
			walkExpr(k, f)
		}
	case *JSXFrag:
		for _, k := range x.Children {
			walkExpr(k, f)
		}
	case *JSXExprChild:
		walkExpr(x.X, f)
	}
}
