package compiler

// JS 后端: 组件 → 函数, useState → signal, 依赖 signal 的 const → memo, JSX → el/t/text/cond/each。
// 读取 signal/memo 的地方改写成 name()。

import (
	"fmt"
	"strconv"
	"strings"
)

type jsGen struct {
	c   *Checker
	m   *Module
	b   strings.Builder
	ind int
}

func (g *jsGen) fail(pos Pos, format string, args ...any) {
	panic(&genError{Pos: pos, Msg: fmt.Sprintf(format, args...)})
}

func (g *jsGen) line(format string, args ...any) {
	g.b.WriteString(strings.Repeat("  ", g.ind))
	fmt.Fprintf(&g.b, format, args...)
	g.b.WriteByte('\n')
}

func GenJS(c *Checker, m *Module) (src string, err error) {
	g := &jsGen{c: c, m: m}
	defer func() {
		if r := recover(); r != nil {
			if ge, ok := r.(*genError); ok {
				err = ge
				return
			}
			panic(r)
		}
	}()
	g.line("// Code generated by gotsx from %s. DO NOT EDIT.", m.File)
	g.line(`import * as G from "./runtime.js";`)
	for _, im := range m.Imports {
		if im.From == "gotsx" || strings.HasPrefix(im.From, "host:") || im.TypeOnly {
			continue
		}
		dep := c.resolveImport(m, im.From, im.Pos)
		if dep.Kind == "server" {
			continue
		}
		var parts []string
		if im.Default != "" {
			parts = append(parts, im.Default)
		}
		var named []string
		for _, n := range im.Names {
			if n.TypeOnly {
				continue
			}
			if _, isType := dep.Scope.types[n.Name]; isType && dep.Exports[n.Name] == nil {
				continue
			}
			if n.Local == n.Name {
				named = append(named, n.Name)
			} else {
				named = append(named, n.Name+" as "+n.Local)
			}
		}
		if len(named) > 0 {
			parts = append(parts, "{ "+strings.Join(named, ", ")+" }")
		}
		if len(parts) > 0 {
			g.line("import %s from %q;", strings.Join(parts, ", "), "./"+dep.Name+".js")
		}
	}
	g.line("")
	for _, s := range m.Stmts {
		switch d := s.(type) {
		case *FuncDecl:
			g.funcDecl(d, true)
		case *InterfaceDecl, *TypeAlias, *EmptyStmt:
		case *ExportDefault:
			g.line("export default %s;", g.expr(d.X))
		case *VarDecl:
			prefix := ""
			if d.Export {
				prefix = "export "
			}
			g.line("%sconst %s = %s;", prefix, d.Pat.Name, g.expr(d.Init))
		default:
			g.fail(Pos{}, "JS backend: unsupported module-level %T", s)
		}
	}
	return g.b.String(), nil
}

func (g *jsGen) funcDecl(d *FuncDecl, top bool) {
	prefix := ""
	if top && d.Export {
		prefix = "export "
		if d.Default {
			prefix = "export default "
		}
	}
	async := ""
	if d.Async {
		async = "async "
	}
	g.line("%s%sfunction %s(%s) {", prefix, async, d.Name, g.params(d.Params))
	g.ind++
	g.stmts(d.Body.Stmts)
	g.ind--
	g.line("}")
	if top {
		g.line("")
	}
}

func (g *jsGen) params(ps []*Param) string {
	var out []string
	for _, p := range ps {
		out = append(out, g.pattern(p.Pat))
	}
	return strings.Join(out, ", ")
}

func (g *jsGen) pattern(p *Pattern) string {
	switch p.Kind {
	case PatObject:
		var ps []string
		for _, pp := range p.Props {
			s := pp.Key
			if !(pp.Pat.Kind == PatIdent && pp.Pat.Name == pp.Key) {
				s = pp.Key + ": " + g.pattern(pp.Pat)
			}
			if pp.Default != nil {
				s += " = " + g.expr(pp.Default)
			}
			ps = append(ps, s)
		}
		if p.Rest != nil {
			ps = append(ps, "..."+g.pattern(p.Rest))
		}
		return "{ " + strings.Join(ps, ", ") + " }"
	case PatArray:
		var ps []string
		for _, e := range p.Elems {
			ps = append(ps, g.pattern(e))
		}
		if p.Rest != nil {
			ps = append(ps, "..."+g.pattern(p.Rest))
		}
		return "[" + strings.Join(ps, ", ") + "]"
	}
	return p.Name
}

func (g *jsGen) stmts(ss []Stmt) {
	for _, s := range ss {
		g.stmt(s)
	}
}

func (g *jsGen) block(b *Block) {
	g.ind++
	g.stmts(b.Stmts)
	g.ind--
}

func (g *jsGen) stmt(s Stmt) {
	switch d := s.(type) {
	case *VarDecl:
		kw := "let"
		if d.Const {
			kw = "const"
		}
		switch d.Hook {
		case "useState":
			call := d.Init.(*Call)
			g.line("const [%s, %s] = G.signal(%s);", d.Pat.Elems[0].Name, d.Pat.Elems[1].Name, g.expr(call.Args[0]))
		case "memo":
			if call, ok := d.Init.(*Call); ok && call.Kind == "hook:useMemo" {
				g.line("const %s = G.memo(%s);", d.Pat.Name, g.expr(call.Args[0]))
			} else {
				g.line("const %s = G.memo(() => %s);", d.Pat.Name, g.expr(d.Init))
			}
		default:
			if d.Init == nil {
				g.line("%s %s;", kw, g.pattern(d.Pat))
			} else {
				g.line("%s %s = %s;", kw, g.pattern(d.Pat), g.expr(d.Init))
			}
		}
	case *ReturnStmt:
		if d.X == nil {
			g.line("return;")
			break
		}
		rt := unopt(d.X.T())
		nodeLike := isNode(rt)
		if at, ok := rt.(*ArrT); ok && isNode(at.Elem) {
			nodeLike = true
		}
		if nodeLike { // 组件根返回若是条件/列表, 也要保持响应式
			g.line("return %s;", g.nodeExpr(d.X, false))
		} else {
			g.line("return %s;", g.expr(d.X))
		}
	case *IfStmt:
		g.line("if (%s) {", g.expr(d.Cond))
		g.block(d.Then)
		if d.Else != nil {
			switch e := d.Else.(type) {
			case *Block:
				g.line("} else {")
				g.block(e)
			case *IfStmt:
				g.line("} else {")
				g.ind++
				g.stmt(e)
				g.ind--
			}
		}
		g.line("}")
	case *ForOfStmt:
		g.line("for (const %s of %s) {", g.pattern(d.Pat), g.expr(d.Iter))
		g.block(d.Body)
		g.line("}")
	case *WhileStmt:
		g.line("while (%s) {", g.expr(d.Cond))
		g.block(d.Body)
		g.line("}")
	case *ForStmt:
		init, cond, post := "", "", ""
		if d.Init != nil {
			switch i := d.Init.(type) {
			case *VarDecl:
				init = "let " + g.pattern(i.Pat)
				if i.Init != nil {
					init += " = " + g.expr(i.Init)
				}
			case *ExprStmt:
				init = g.expr(i.X)
			}
		}
		if d.Cond != nil {
			cond = g.expr(d.Cond)
		}
		if d.Update != nil {
			post = g.expr(d.Update)
		}
		g.line("for (%s; %s; %s) {", init, cond, post)
		g.block(d.Body)
		g.line("}")
	case *BreakStmt:
		g.line("break;")
	case *ContinueStmt:
		g.line("continue;")
	case *SwitchStmt:
		g.line("switch (%s) {", g.expr(d.Disc))
		g.ind++
		for _, cs := range d.Cases {
			if cs.Test == nil {
				g.line("default:")
			} else {
				g.line("case %s:", g.expr(cs.Test))
			}
			g.ind++
			g.stmts(cs.Body)
			g.ind--
		}
		g.ind--
		g.line("}")
	case *ExprStmt:
		if call, ok := d.X.(*Call); ok && call.Kind == "hook:useEffect" {
			g.line("G.effect(%s);", g.expr(call.Args[0]))
			return
		}
		if call, ok := d.X.(*Call); ok && call.Kind == "hook:useEffectOnce" {
			g.line("G.onMount(%s);", g.expr(call.Args[0]))
			return
		}
		g.line("%s;", g.expr(d.X))
	case *Block:
		g.line("{")
		g.block(d)
		g.line("}")
	case *TryStmt:
		g.line("try {")
		g.block(d.Body)
		if d.Catch != nil {
			if d.CatchName != "" {
				g.line("} catch (%s) {", d.CatchName)
			} else {
				g.line("} catch {")
			}
			g.block(d.Catch)
		}
		if d.Finally != nil {
			g.line("} finally {")
			g.block(d.Finally)
		}
		g.line("}")
	case *ThrowStmt:
		g.line("throw %s;", g.expr(d.X))
	case *FuncDecl:
		g.funcDecl(d, false)
	case *InterfaceDecl, *TypeAlias, *EmptyStmt:
	default:
		g.fail(Pos{}, "JS backend: unsupported statement %T", s)
	}
}

func (g *jsGen) expr(e Expr) string {
	switch x := e.(type) {
	case *Ident:
		if x.Sym != nil && (x.Sym.Kind == SSignal || x.Sym.Kind == SMemo) {
			return x.Name + "()"
		}
		if x.Sym != nil && x.Sym.Kind == SHostMember && x.Sym.Host != nil && x.Sym.Host.Action { // an action passed as a value
			return "((...a) => G.act(" + jsQuote(x.Sym.Host.Mod) + ", " + jsQuote(x.Sym.Host.Name) + ", a))"
		}
		if x.Sym != nil && x.Sym.Kind == SBuiltin {
			switch x.Sym.Name {
			case "emit", "on", "jsonLd":
				return "G." + x.Sym.Name
			case "t":
				return "G.tr"
			case "tv":
				return "G.trv"
			case "plural":
				return "G.plural"
			case "fmtNum":
				return "G.fmtNum"
			case "fmtCur":
				return "G.fmtCur"
			case "fmtDate":
				return "G.fmtDate"
			case "lpath":
				return "G.lpath"
			case "isoDate":
				return "G.isoDate"
			}
		}
		return x.Name
	case *NumLit:
		return x.Raw
	case *RegexLit:
		return "/" + x.Pattern + "/" + x.Flags
	case *StrLit:
		return jsQuote(x.Val)
	case *BoolLit:
		if x.Val {
			return "true"
		}
		return "false"
	case *NullLit:
		return "undefined"
	case *TemplateLit:
		var b strings.Builder
		b.WriteByte('`')
		for i, q := range x.Quasis {
			b.WriteString(strings.NewReplacer("\\", "\\\\", "`", "\\`", "${", "\\${").Replace(q))
			if i < len(x.Exprs) {
				b.WriteString("${" + g.expr(x.Exprs[i]) + "}")
			}
		}
		b.WriteByte('`')
		return b.String()
	case *ArrayLit:
		var es []string
		for _, el := range x.Elems {
			es = append(es, g.expr(el))
		}
		return "[" + strings.Join(es, ", ") + "]"
	case *ObjectLit:
		var ps []string
		for _, p := range x.Props {
			if p.Spread != nil {
				ps = append(ps, "..."+g.expr(p.Spread))
			} else {
				ps = append(ps, jsKey(p.Key)+": "+g.expr(p.Val))
			}
		}
		return "{ " + strings.Join(ps, ", ") + " }"
	case *Member:
		return g.mapRead(g.lval(x), x)
	case *Index:
		return g.mapRead(g.lval(x), x)
	case *Call:
		if x.Kind == "hook:useMemo" {
			return "G.memo(" + g.expr(x.Args[0]) + ")"
		}
		if x.Kind == "hook:createStore" { // export const cart = createStore(init) → G.store(key, init) — every field present (missing = zero value)
			st := x.T().(*StoreT)
			return "G.store(" + jsQuote(st.Sym.Go) + ", " + g.storeInit(x.Args[0], st.State) + ")"
		}
		if x.Kind == "action" { // await toggle(id) → G.act("todos", "toggle", [id])
			var args []string
			for _, a := range x.Args {
				args = append(args, g.expr(a))
			}
			return "G.act(" + jsQuote(x.Host.Mod) + ", " + jsQuote(x.Host.Name) + ", [" + strings.Join(args, ", ") + "])"
		}
		if s := g.builtinJS(x); s != "" {
			return s
		}
		var args []string
		for _, a := range x.Args {
			args = append(args, g.expr(a))
		}
		callee := g.expr(x.Fn)
		if x.Optional {
			callee += "?."
		}
		return callee + "(" + strings.Join(args, ", ") + ")"
	case *Unary:
		if x.Op == "typeof" || x.Op == "delete" {
			return x.Op + " " + g.lval(x.X)
		}
		return x.Op + g.expr(x.X)
	case *Binary:
		op := x.Op
		if op == "??" { // 与 Go 后端一致: 原始类型用零值表示缺席, ?? 与 || 同义
			if t := unopt(x.T()); t == TString || t == TNumber || t == TBool {
				op = "||"
			}
		}
		if (op == "===" || op == "!==") && g.nullCmp(x) != "" {
			return g.nullCmp(x)
		}
		return "(" + g.expr(x.L) + " " + op + " " + g.expr(x.R) + ")"
	case *Update:
		if x.Prefix {
			return x.Op + g.lval(x.X)
		}
		return g.lval(x.X) + x.Op
	case *CondExpr:
		return "(" + g.expr(x.Test) + " ? " + g.expr(x.Then) + " : " + g.expr(x.Else) + ")"
	case *Arrow:
		async := ""
		if x.Async {
			async = "async "
		}
		if x.ExprBody != nil {
			body := g.expr(x.ExprBody)
			if _, isObj := x.ExprBody.(*ObjectLit); isObj {
				body = "(" + body + ")"
			}
			return async + "(" + g.params(x.Params) + ") => " + body
		}
		var b strings.Builder
		fmt.Fprintf(&b, "%s(%s) => {\n", async, g.params(x.Params))
		sub := &jsGen{c: g.c, m: g.m, ind: g.ind + 1}
		sub.stmts(x.Body.Stmts)
		b.WriteString(sub.b.String())
		b.WriteString(strings.Repeat("  ", g.ind) + "}")
		return b.String()
	case *Assign:
		return g.lval(x.Target) + " " + x.Op + " " + g.expr(x.Val)
	case *AsExpr:
		return g.expr(x.X)
	case *AwaitExpr:
		return "(await " + g.expr(x.X) + ")"
	case *SpreadExpr:
		return "..." + g.expr(x.X)
	case *NonNull:
		return g.expr(x.X)
	case *Paren:
		return "(" + g.expr(x.X) + ")"
	case *JSXElem:
		return g.jsxElem(x)
	case *JSXFrag:
		return "[" + g.children(x.Children) + "]"
	case *JSXText:
		return "G.t(" + jsQuote(normalizeJSXText(x.Text)) + ")"
	case *JSXExprChild:
		return g.child(x)
	}
	g.fail(e.GetPos(), "JS backend: unsupported expression %T", e)
	return ""
}

// lval: 成员 / 下标的原始形式(赋值目标、delete、++ 用), 不做 Record 零值补齐
func (g *jsGen) lval(e Expr) string {
	switch x := e.(type) {
	case *Member:
		if _, ok := x.X.T().(*StoreT); ok && x.Name != "set" { // cart.count: a signal read
			return g.expr(x.X) + "." + x.Name + "()"
		}
		if x.Optional {
			return g.expr(x.X) + "?." + x.Name
		}
		return g.expr(x.X) + "." + x.Name
	case *Index:
		return g.expr(x.X) + "[" + g.expr(x.I) + "]"
	case *Paren:
		return "(" + g.lval(x.X) + ")"
	}
	return g.expr(e)
}

// zeroJS: 原始类型的零值字面量; 其它类型返回 ""
func zeroJS(t Type) string {
	switch unopt(t) {
	case TString:
		return `""`
	case TNumber:
		return "0"
	case TBool:
		return "false"
	}
	return ""
}

// zeroValue: the JS zero value of a dialect type (what the Go side has for an absent field)
func (g *jsGen) zeroValue(t Type) string {
	if z := zeroJS(t); z != "" {
		return z
	}
	switch x := t.(type) {
	case *OptT:
		if _, isObj := x.Elem.(*ObjT); isObj {
			return "undefined"
		}
		return g.zeroValue(x.Elem)
	case *ArrT:
		return "[]"
	case *MapT:
		return "{}"
	case *ObjT:
		var ps []string
		for _, f := range x.Fields {
			ps = append(ps, jsKey(f.Name)+": "+g.zeroValue(f.Type))
		}
		return "{ " + strings.Join(ps, ", ") + " }"
	}
	return "undefined"
}

// storeInit: the initial state of a store with every field of the state type present, so the store has a signal per
// field (a literal may omit fields: they are zero values, as on the Go side)
func (g *jsGen) storeInit(init Expr, state *ObjT) string {
	lit, ok := init.(*ObjectLit)
	if !ok {
		return "Object.assign(" + g.zeroValue(state) + ", " + g.expr(init) + ")"
	}
	given := map[string]Expr{}
	for _, p := range lit.Props {
		if p.Spread != nil {
			return "Object.assign(" + g.zeroValue(state) + ", " + g.expr(init) + ")"
		}
		given[p.Key] = p.Val
	}
	var ps []string
	for _, f := range state.Fields {
		if v, ok := given[f.Name]; ok {
			ps = append(ps, jsKey(f.Name)+": "+g.expr(v))
		} else {
			ps = append(ps, jsKey(f.Name)+": "+g.zeroValue(f.Type))
		}
	}
	return "{ " + strings.Join(ps, ", ") + " }"
}

// mapRead: 读 Record 的键 —— 与 Go 的 map 一致, 缺席的键给值类型的零值(m.k ?? ""), 用 Object.hasOwn 判断存在
func (g *jsGen) mapRead(raw string, e Expr) string {
	var recv Expr
	switch x := e.(type) {
	case *Member:
		if !x.MapKey {
			return raw
		}
		recv = x.X
	case *Index:
		recv = x.X
	}
	if _, ok := unopt(recv.T()).(*MapT); !ok {
		return raw
	}
	if z := zeroJS(e.T()); z != "" {
		return "(" + raw + " ?? " + z + ")"
	}
	return raw
}

// nullCmp: x === undefined / null 对原始类型比较零值(两端一致: 缺席 = 零值); 非原始类型返回 ""
func (g *jsGen) nullCmp(x *Binary) string {
	other := x.L
	if _, ok := x.L.(*NullLit); ok {
		other = x.R
	} else if _, ok := x.R.(*NullLit); !ok {
		return ""
	}
	z := zeroJS(other.T())
	if z == "" {
		return ""
	}
	op := "==="
	if x.Op == "!==" {
		op = "!=="
	}
	inner := g.expr(other)
	if !isMapRead(other) { // Record 读取已经补过零值
		inner = "(" + inner + " ?? " + z + ")"
	}
	return "(" + inner + " " + op + " " + z + ")"
}

func isMapRead(e Expr) bool {
	switch x := e.(type) {
	case *Paren:
		return isMapRead(x.X)
	case *Member:
		return x.MapKey
	case *Index:
		_, ok := unopt(x.X.T()).(*MapT)
		return ok
	}
	return false
}

// builtinJS: 少数方法要和 Go 后端逐字节一致(copy 而非原地改、越界零值、map 键排序), 走运行时 G.*
func (g *jsGen) builtinJS(x *Call) string {
	m, ok := x.Fn.(*Member)
	if !ok {
		return ""
	}
	a := func(i int) string {
		if i < len(x.Args) {
			return g.expr(x.Args[i])
		}
		return "undefined"
	}
	recv := func() string { return g.expr(m.X) }
	switch strings.TrimPrefix(x.Kind, "builtin:") {
	case "re_match":
		return "G.match(" + recv() + ", " + a(0) + ")"
	case "re_replaceAll":
		return recv() + ".replace(" + a(0) + ", " + a(1) + ")" // g 标志已由 checker 保证
	}
	switch m.Builtin {
	case "sort":
		return "G.sort(" + recv() + ", " + a(0) + ")"
	case "at":
		return "G.at(" + recv() + ", " + a(0) + ")"
	case "reverse":
		return "G.reverse(" + recv() + ")"
	case "localeCompare":
		return "G.cmp(" + recv() + ", " + a(0) + ")"
	}
	// Object.keys / Object.values: 排序键, 与 Go map 一致
	if id, ok := m.X.(*Ident); ok && id.Name == "Object" {
		if m.Name == "keys" {
			return "G.objectKeys(" + a(0) + ")"
		}
		if m.Name == "values" {
			return "G.objectValues(" + a(0) + ")"
		}
	}
	return ""
}

func jsQuote(s string) string { return strconv.Quote(s) }

func jsKey(k string) string {
	for i, r := range k {
		if !(r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (i > 0 && r >= '0' && r <= '9')) {
			return jsQuote(k)
		}
	}
	return k
}

// ---------- JSX ----------

// children: 相邻的静态文本(字面量 + 非响应式字符串/数字表达式)合并成一个 G.t(a + b) ——
// 服务端把它们输出成相邻文本, HTML 解析后是同一个文本节点, hydrate 认领必须一一对应。
func (g *jsGen) children(kids []Expr) string {
	var out []string
	var run []string
	flush := func() {
		if len(run) > 0 {
			out = append(out, "G.t("+strings.Join(run, " + ")+")")
			run = nil
		}
	}
	for _, k := range kids {
		switch x := k.(type) {
		case *JSXText:
			s := normalizeJSXText(x.Text)
			if s == "" {
				continue
			}
			run = append(run, jsQuote(s))
		case *JSXExprChild:
			if x.X == nil {
				continue
			}
			if g.isStaticText(x) {
				run = append(run, "String("+g.expr(x.X)+")")
				continue
			}
			flush()
			out = append(out, g.child(x))
		default:
			flush()
			out = append(out, g.expr(k))
		}
	}
	flush()
	return strings.Join(out, ", ")
}

func (g *jsGen) isStaticText(x *JSXExprChild) bool {
	if x.Reactive {
		return false
	}
	e := x.X
	for {
		p, ok := e.(*Paren)
		if !ok {
			break
		}
		e = p.X
	}
	switch e.(type) {
	case *Binary, *CondExpr, *Call, *JSXElem, *JSXFrag:
		// && / 三元 / map 可能是节点, 交给 child(); 普通调用(如 fmtNumber(x))是文本
		if _, isCall := e.(*Call); !isCall {
			return false
		}
	}
	t := unopt(e.T())
	return t == TString || t == TNumber
}

// child: {expr} 子节点 → 运行时调用
func (g *jsGen) child(x *JSXExprChild) string {
	return g.nodeExpr(x.X, x.Reactive)
}

// nodeExpr: 把节点位置的表达式编成运行时调用, 递归保持嵌套条件/列表的响应式。
// reactive 从外层继承(响应式 cond 的分支里, 内层也要响应式)。
func (g *jsGen) nodeExpr(e Expr, reactive bool) string {
	for {
		p, ok := e.(*Paren)
		if !ok {
			break
		}
		e = p.X
	}
	t := unopt(e.T())
	nodeLike := isNode(t)
	if at, ok := t.(*ArrT); ok && isNode(at.Elem) {
		nodeLike = true
	}
	// 标记(marker)必须与 Go 后端逐一对应: 每个构造用它自己的 .Reactive, 不从外层继承。
	// 递归进入分支时 leaf 文本的 reactive 传 false —— 分支由外层响应式块整体重建, 内部文本是静态的。
	switch y := e.(type) {
	case *Binary:
		if y.Op == "&&" && nodeLike {
			if y.Reactive {
				return "G.cond(() => " + g.expr(y.L) + ", () => " + g.nodeExpr(y.R, false) + ")"
			}
			return "(" + g.expr(y.L) + " && " + g.nodeExpr(y.R, false) + ")"
		}
	case *CondExpr:
		if nodeLike {
			if y.Reactive {
				return "G.cond(() => " + g.expr(y.Test) + ", () => " + g.nodeExpr(y.Then, false) + ", () => " + g.nodeExpr(y.Else, false) + ")"
			}
			return "(" + g.expr(y.Test) + " ? " + g.nodeExpr(y.Then, false) + " : " + g.nodeExpr(y.Else, false) + ")"
		}
	case *Call:
		if m, ok := y.Fn.(*Member); ok && m.Builtin == "map" && y.Reactive {
			return "G.each(() => " + g.expr(m.X) + ", " + g.expr(y.Args[0]) + g.keyFn(y.Args[0]) + ")"
		}
	}
	switch tt := t.(type) {
	case *Prim:
		switch tt {
		case TNode:
			if id, ok := e.(*Ident); ok && id.Sym != nil && id.Sym.Kind == SParam {
				return "G.kids(" + g.expr(e) + ")" // children 可能是 thunk
			}
			return g.expr(e)
		case TString, TNumber, TAny:
			if reactive {
				return "G.text(() => " + g.expr(e) + ")"
			}
			return "G.t(String(" + g.expr(e) + "))"
		case TBool, TUndef:
			return "null"
		}
	case *ArrT:
		if isNode(tt.Elem) {
			return g.expr(e)
		}
		return "G.t(" + g.expr(e) + `.join(""))`
	}
	g.fail(e.GetPos(), "JS backend: cannot use %s as a JSX child", t)
	return ""
}

// keyFn: list.map((x) => <li key={x.id}>…</li>) 的 key 表达式 → ", (x) => x.id"; 没有 key 返回 ""
// 有 key 的列表在客户端按 key 复用/移动 DOM(输入框状态不丢), 没有 key 的整块重建。
func (g *jsGen) keyFn(cb Expr) string {
	a, ok := cb.(*Arrow)
	if !ok {
		return ""
	}
	var root Expr = a.ExprBody
	if root == nil && a.Body != nil && len(a.Body.Stmts) > 0 {
		if r, ok := a.Body.Stmts[len(a.Body.Stmts)-1].(*ReturnStmt); ok {
			root = r.X
		}
	}
	for {
		p, ok := root.(*Paren)
		if !ok {
			break
		}
		root = p.X
	}
	el, ok := root.(*JSXElem)
	if !ok {
		return ""
	}
	for _, at := range el.Attrs {
		if at.Name == "key" && at.Val != nil {
			return ", (" + g.params(a.Params) + ") => " + g.expr(at.Val)
		}
	}
	return ""
}

func (g *jsGen) jsxElem(x *JSXElem) string {
	if x.Comp != nil {
		var ps []string
		for _, a := range x.Attrs {
			if a.Name == "key" {
				continue
			}
			if a.Val == nil {
				ps = append(ps, jsKey(a.Name)+": true")
				continue
			}
			ps = append(ps, jsKey(a.Name)+": "+g.expr(a.Val))
		}
		if len(x.Children) > 0 {
			ps = append(ps, "children: () => ["+g.children(x.Children)+"]")
		}
		return x.Comp.Name + "({ " + strings.Join(ps, ", ") + " })"
	}
	var attrs []string
	for _, a := range x.Attrs {
		if a.Name == "key" {
			continue
		}
		key := jsKey(a.Name)
		if a.Val == nil {
			attrs = append(attrs, key+": true")
			continue
		}
		if _, isStr := a.Val.(*StrLit); isStr || strings.HasPrefix(a.Name, "on") || !a.Reactive {
			attrs = append(attrs, key+": "+g.expr(a.Val))
			continue
		}
		attrs = append(attrs, key+": () => "+g.expr(a.Val))
	}
	as := "null"
	if len(attrs) > 0 {
		as = "{ " + strings.Join(attrs, ", ") + " }"
	}
	kids := g.children(x.Children)
	if kids == "" {
		return "G.el(" + jsQuote(x.Tag) + ", " + as + ")"
	}
	return "G.el(" + jsQuote(x.Tag) + ", " + as + ", () => [" + kids + "])"
}
