// Generated by gotsx from the Go host modules. DO NOT EDIT.

declare module "host:auth" {
  /** action: callable from islands (POST, same-origin); throws on a validation error */
  export function login(user: string, pass: string): Promise<Profile>;
  /** action: callable from islands (POST, same-origin); throws on a validation error */
  export function logout(): Promise<void>;
}

declare module "host:stats" {
  export function cards(): Stat[];
  export function recent(): Activity[];
}

declare module "host:users" {
  /** action: callable from islands (POST, same-origin); throws on a validation error */
  export function all(): Promise<UserPage>;
  /** action: callable from islands (POST, same-origin); throws on a validation error */
  export function create(name: string, email: string, role: string, dept: string): Promise<User>;
  export function get(id: string): User;
  export function query(q: string, role: string, sortBy: string, page: number): UserPage;
  /** action: callable from islands (POST, same-origin); throws on a validation error */
  export function remove(id: string): Promise<void>;
  /** action: callable from islands (POST, same-origin); throws on a validation error */
  export function update(id: string, name: string, email: string, role: string, dept: string, status: string): Promise<User>;
}

declare module "host:data" {
  export interface Profile {
    user: string;
    name: string;
    role: string;
  }
  export interface Stat {
    label: string;
    value: string;
    delta: string;
    up: boolean;
    icon: string;
  }
  export interface Activity {
    who: string;
    what: string;
    when: string;
    icon: string;
  }
  export interface UserPage {
    items: User[];
    total: number;
    page: number;
    pages: number;
    pageList: number[];
    active: number;
    admins: number;
  }
  export interface User {
    id: string;
    name: string;
    email: string;
    role: string;
    status: string;
    dept: string;
    created: string;
    lastSeen: string;
  }
}
