package main

// AGENTS.md / CLAUDE.md and the docs that ship with the CLI version (app/.gen/docs/): a coding agent first reads
// "this is not React/Next", then the conventions matching the current gotsx version — modeled on Next.js's managed AGENTS.md block.

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

//go:embed docs/*.md
var agentDocs embed.FS

const (
	agentBlockBegin = "<!-- BEGIN:gotsx-agent-rules -->"
	agentBlockEnd   = "<!-- END:gotsx-agent-rules -->"
)

// agentBlock: the block in AGENTS.md maintained by gotsx (build/dev upgrade it; content outside the block belongs to the project and is untouched)
func agentBlock() string {
	return agentBlockBegin + `
# This is gotsx, not React or Next.js

gotsx compiles a static TSX dialect to Go. The JSX looks familiar, but there is no React runtime, no npm,
no ` + "`async`" + ` on the server, no DOM in ` + "`.server.tsx`" + ` files, and only a typed subset of TypeScript compiles
(a compile error with file:line:col otherwise). Your training data does not describe this version.

Before writing or changing code, read the version-matched docs in ` + "`app/.gen/docs/`" + ` (written by
` + "`gotsx build`" + ` for the exact gotsx version in go.mod): start with ` + "`index.md`" + `, then ` + "`language.md`" + ` (the exact syntax table),
` + "`conventions.md`" + ` (pages, layouts, islands, host modules, typed actions, sessions), ` + "`runtime.md`" + ` (the Go side),
` + "`errors.md`" + ` (what each error means and its fix) and ` + "`agent-workflow.md`" + ` (check → dev → verify loop).

Rules that are always true:
- Never edit ` + "`gen/`" + ` or ` + "`app/.gen/`" + `; they are regenerated by ` + "`gotsx build`" + `. Change ` + "`app/`" + `, ` + "`host/`" + ` and ` + "`main.go`" + ` instead.
- ` + "`gotsx check --json`" + ` is the fast feedback loop; ` + "`gotsx build`" + ` must pass before a commit.
- ` + "`gotsx dev`" + ` writes ` + "`.gotsx/dev.json`" + ` (pid, port, url) while it runs and ` + "`.gotsx/diagnostics.json`" + ` when a build fails.
  Do not start a second ` + "`gotsx dev`" + `; read the state file and use the running server.
- Islands (` + "`.client.tsx`" + `) reach Go only through typed actions (methods listed in ` + "`host.Registry[...].Actions`" + `).
` + agentBlockEnd + "\n"
}

// agentsFile: the AGENTS.md written by gotsx new (managed block + project notes)
func agentsFile(name string) string {
	return agentBlock() + `
# ` + name + `

Project notes for humans and agents — edit freely; only the block above is managed by gotsx.

- ` + "`gotsx dev`" + ` — build, run, watch (browser reloads; compile errors show in the browser and in ` + "`.gotsx/diagnostics.json`" + `)
- ` + "`gotsx check`" + ` — type-check the dialect without building
- ` + "`gotsx build && go build`" + ` — one static binary with everything embedded
- ` + "`go test ./...`" + ` — Go tests (host package, handlers)
`
}

const claudeFile = "@AGENTS.md\n"

// ensureAgentFiles maintains the managed block in AGENTS.md on build/dev (upgrades it in an existing file; creates the file at a module root) and writes CLAUDE.md
func ensureAgentFiles(dir string) {
	writeAgentDocs(dir)
	p := filepath.Join(dir, "AGENTS.md")
	raw, err := os.ReadFile(p)
	switch {
	case err == nil:
		cur := string(raw)
		i, j := strings.Index(cur, agentBlockBegin), strings.Index(cur, agentBlockEnd)
		var next string
		if i >= 0 && j > i {
			next = cur[:i] + strings.TrimSuffix(agentBlock(), "\n") + cur[j+len(agentBlockEnd):]
		} else {
			next = agentBlock() + "\n" + cur
		}
		if next != cur {
			os.WriteFile(p, []byte(next), 0o644)
		}
	case fileExists(filepath.Join(dir, "go.mod")): // create only at a module root (subdirectory demos inside a repo get none)
		os.WriteFile(p, []byte(agentsFile(filepath.Base(dir))), 0o644)
	default:
		return
	}
	if cp := filepath.Join(dir, "CLAUDE.md"); !fileExists(cp) {
		os.WriteFile(cp, []byte(claudeFile), 0o644)
	}
}

// writeAgentDocs: app/.gen/docs/*.md — the docs matching this CLI version (unchanged content is not rewritten, so the watcher is not triggered)
func writeAgentDocs(dir string) {
	out := filepath.Join(dir, "app", ".gen", "docs")
	entries, _ := fs.ReadDir(agentDocs, "docs")
	if len(entries) == 0 {
		return
	}
	os.MkdirAll(out, 0o755)
	for _, e := range entries {
		b, _ := agentDocs.ReadFile("docs/" + e.Name())
		content := strings.ReplaceAll(string(b), "{{version}}", version())
		p := filepath.Join(out, e.Name())
		if old, err := os.ReadFile(p); err == nil && string(old) == content {
			continue
		}
		os.WriteFile(p, []byte(content), 0o644)
	}
}

// printDoc: gotsx docs [name]
func printDoc(name string) error {
	name = strings.TrimSuffix(name, ".md")
	b, err := agentDocs.ReadFile("docs/" + name + ".md")
	if err != nil {
		entries, _ := fs.ReadDir(agentDocs, "docs")
		var names []string
		for _, e := range entries {
			names = append(names, strings.TrimSuffix(e.Name(), ".md"))
		}
		return fmt.Errorf("no doc named %q; available: %s", name, strings.Join(names, ", "))
	}
	fmt.Print(strings.ReplaceAll(string(b), "{{version}}", version()))
	return nil
}
