// Generated by gotsx. DO NOT EDIT. Editor-only typings for the gotsx dialect.

declare module "gotsx" {
  /** A rendered node (JSX). */
  export type Node = JSX.Element;
  /** A one-shot message queued by an action (req.Session().Flash) and delivered to the next page. */
  export interface Flash { kind: string; text: string; }
  /** Props every page component receives. */
  export interface PageProps {
    params: Record<string, string>;
    query: Record<string, string>;
    path: string;
    locale: string;
    cookies: Record<string, string>;
    /** Session values (read-only here; write them in actions via req.Session()). */
    session: Record<string, string>;
    /** Flash messages consumed by this render. */
    flash: Flash[];
    /** CSRF token for classic <form method="post"> handlers (name="_csrf"). */
    csrf: string;
  }
  /** Props of pages/**\/_layout.server.tsx: the page props plus the wrapped content. */
  /** Page metadata: a page exports "function meta(props: PageProps): Meta"; layouts read it as props.meta. */
  export interface Meta { title?: string; description?: string; canonical?: string; image?: string; noIndex?: boolean; }
  export interface LayoutProps extends PageProps { meta: Meta; children: Node; }
  /** Props of pages/_error.server.tsx. */
  export interface ErrorProps extends PageProps { message: string; }
  /** Streaming boundary (server components only): the fallback ships with the shell, children render afterwards in their own goroutine. */
  export function Suspense(props: { fallback: Node; children?: Node }): Node;
  /** Server: the initial value. Client: a signal. */
  export function useState<T>(init: T): [T, (v: T | ((prev: T) => T)) => void];
  /** Client only. deps [] = run once on mount; otherwise dependencies are tracked automatically. */
  export function useEffect(fn: () => void, deps?: unknown[]): void;
  export function useMemo<T>(fn: () => T): T;
  /** Cross-island event bus (client only). */
  export function emit(name: string, detail?: unknown): void;
  export function on(name: string, fn: (detail: any) => void): void;
}

declare global {
  namespace JSX {
    interface Element {}
    interface ElementChildrenAttribute { children: {} }
    interface IntrinsicElements { [tag: string]: any }
  }
  /** i18n (server + client). */
  function t(locale: string, key: string): string;
  function tv(locale: string, key: string, vars: Record<string, string>): string;
  function plural(locale: string, key: string, n: number): string;
  function fmtNum(locale: string, n: number): string;
  function fmtCur(locale: string, cents: number): string;
  function fmtDate(locale: string, iso: string): string;
  function lpath(locale: string, path: string): string;
  /** Safe JSON-LD <script> (pass JSON.stringify(...)). */
  function jsonLd(json: string): JSX.Element;
  /** Server only: abort rendering and respond with a redirect (default 302). */
  function redirect(url: string, status?: number): JSX.Element;
  /** Server only: abort rendering and respond with the 404 page. */
  function notFound(): JSX.Element;
}

export {};
