// Generated by gotsx from the Go host modules. DO NOT EDIT.

declare module "host:hl" {
  export function tokens(arg0: string, arg1: string): Token[];
}

declare module "host:site" {
  export function goVersion(): string;
  export function now(): string;
  export function version(): string;
}

declare module "host:data" {
  export interface Token {
    kind: string;
    text: string;
  }
}
